"""
Diffractive optical element (DOE), grating, and phase mask functions.

This module provides tools for creating and manipulating phase-only
diffractive elements:

- **Periodic phase masks** -- tile a unit cell across a simulation grid
  using nearest-neighbor resampling.
- **Microlens arrays** -- generate the quadratic phase profile of a
  square-aperture MLA.
- **Dammann gratings** -- design uniform spot-array generators via an
  iterative Fourier transform algorithm (IFTA).
- **Phase file I/O** -- load and save phase arrays in a simple CSV
  format with optional metadata header.
- **FITS I/O** -- load and save complex fields in FITS format (requires
  the optional ``astropy`` dependency).

Author: Andrew Traverso
"""

from __future__ import annotations

import warnings
from typing import Any, Dict, Optional, Tuple, Union

import numpy as np

# ============================================================================
# Phase file I/O
# ============================================================================

def load_phase_file(filepath: str) -> np.ndarray:
    """
    Load a DOE / grating phase profile from a CSV file.

    Reads a comma-separated file of phase values in radians.
    The file may have been generated by :func:`save_phase_file` or by
    an external tool (e.g. the Optopax 12x12 beam splitter .dat file).

    Parameters
    ----------
    filepath : str
        Path to the CSV file.

    Returns
    -------
    phase : ndarray (M×M or M×N)
        Phase in radians.
    """
    phase = np.genfromtxt(filepath, delimiter=',')
    if phase.ndim != 2:
        raise ValueError(f"Expected 2D phase array, got shape {phase.shape}")
    return phase


def save_phase_file(
    filepath: str,
    phase: np.ndarray,
    cell_pixel_size: Optional[float] = None,
    metadata: Optional[Dict[str, Any]] = None,
) -> None:
    """
    Save a phase profile to a CSV file compatible with :func:`load_phase_file`.

    Writes phase values in radians as comma-separated values.
    Optionally prepends a comment header with cell pixel size and
    other metadata so the file is self-describing.

    Parameters
    ----------
    filepath : str
        Output file path (typically .dat or .csv).

    phase : ndarray (M×M)
        Phase in radians.

    cell_pixel_size : float, optional
        Native pixel spacing of the phase array [m]. If provided, written
        to the header so loaders know the physical scale.

    metadata : dict, optional
        Additional key-value pairs to include in the header comment.
        Example: {'phaselevels': 256, 'wavelength_um': 1.31}
    """
    header_lines = []
    if cell_pixel_size is not None:
        header_lines.append(f"cell_pixel_size_um={cell_pixel_size*1e6:.6f}")
        header_lines.append(f"cell_extent_um={phase.shape[0] * cell_pixel_size * 1e6:.3f}")
    header_lines.append(f"shape={phase.shape[0]}x{phase.shape[1]}")
    if metadata:
        for k, v in metadata.items():
            header_lines.append(f"{k}={v}")

    header = ', '.join(header_lines)
    np.savetxt(filepath, phase, delimiter=',', header=header, fmt='%.8f')


# ============================================================================
# Phase masks
# ============================================================================

def create_periodic_phase_mask(
    N: int,
    dx: float,
    phase_cell: np.ndarray,
    cell_pixel_size: float,
) -> np.ndarray:
    """
    Tile a periodic phase element (DOE, grating, etc.) across the simulation grid.

    The element is defined by a single unit cell with its own native pixel size.
    This function resamples it onto the simulation grid using nearest-neighbor
    mapping and tiles it periodically.

    Parameters
    ----------
    N : int
        Simulation grid size (NxN).

    dx : float
        Simulation grid spacing [m].

    phase_cell : ndarray (M×M)
        Phase of one unit cell in radians. The cell has M×M pixels at
        the native pixel spacing.

    cell_pixel_size : float
        Native pixel spacing of the phase cell [m].
        The unit cell extent is phase_cell.shape[0] * cell_pixel_size.

    Returns
    -------
    mask : ndarray (complex, NxN)
        Transmission function (unit amplitude, phase-only), periodically
        tiled across the full simulation grid.

    Notes
    -----
    When the simulation grid spacing dx is larger than cell_pixel_size,
    this performs a downsampling via nearest-neighbor. For smooth phase
    profiles (typical for far-field DOEs), this is adequate. For phase
    masks with sub-pixel features, consider pre-averaging the complex
    transmission exp(i*phase) over each simulation pixel.

    The cell-pixel lookup is closed **periodically** (``index % cell_N``),
    so every cell pixel is hit equally often on a grid-native design and
    the tiling is exactly periodic (v5.30, audit E-M7 -- it used to clamp
    with ``clip``, which folded the last half-pixel of each cell onto the
    last column and injected spurious diffraction orders).
    """
    cell_N = phase_cell.shape[0]
    cell_extent = cell_N * cell_pixel_size

    # Simulation grid coordinates (same axis for x and y on a square grid)
    coord = (np.arange(N) - N / 2) * dx

    # Map each sim coordinate into the unit cell (periodic tiling)
    in_cell = np.mod(coord, cell_extent)

    # Nearest-neighbor pixel index within the cell.  DOE-nit
    # (AUDIT_DOE_GRATING_FREEFORM): use ``round`` for a true nearest-
    # neighbour sample -- ``.astype(int)`` TRUNCATES (a left-edge, half-pixel-
    # biased sample), contradicting the documented "nearest-neighbor" resample
    # (same half-pixel class as the HFPI-1 / from_field binning nits).
    #
    # v5.30 (audit E-M7): close the lattice with ``% cell_N``, NOT
    # ``clip(..., 0, cell_N - 1)``.  ``in_cell`` lives in ``[0, cell_extent)``
    # so ``round(in_cell / cell_pixel_size)`` reaches ``cell_N`` for any sample
    # in the last HALF pixel of the cell -- and the nearest cell pixel there is
    # the WRAPPED one, index 0, not the clipped ``cell_N - 1``.  Clipping folded
    # that whole half-pixel into the last column, breaking the periodicity the
    # function's own docstring promises: measured on the grid-native
    # 8-pixel/cell case (N=256, dx = cell_pixel_size) the per-cell-pixel
    # occupancy was [21, 32, 32, 32, 32, 32, 32, 43] (spread 22 of 32) instead
    # of a uniform 32, 2816 of 65536 mask pixels carried the wrong phase
    # (max|dt| = 2.0, a full 0<->pi flip), and the tiled 0/pi 50 %-duty binary
    # grating leaked 11.3 % of its power OFF the order lattice with 2.95 %
    # landing in the EVEN (nominally forbidden) orders -- both exactly 0 with
    # the modulo close.
    idx = np.round(in_cell / cell_pixel_size).astype(int) % cell_N
    ix = idx
    iy = idx

    # Build 2D phase by indexing into the unit cell
    IX, IY = np.meshgrid(ix, iy)
    phase_tiled = phase_cell[IY, IX]

    return np.exp(1j * phase_tiled)


def create_microlens_array(
    N: int,
    dx: float,
    n_lenslets: int,
    pitch: float,
    focal_length: float,
    wavelength: float,
) -> np.ndarray:
    """
    Create a microlens array (MLA) phase mask.

    Each lenslet is a thin converging lens (quadratic phase) centered on its
    array position, with a square aperture equal to the pitch. Lenslets do not
    overlap; each pixel on the grid belongs to exactly one lenslet.

    Parameters
    ----------
    N : int
        Simulation grid size (NxN).

    dx : float
        Grid spacing [m].

    n_lenslets : int
        Number of lenslets per side (total lenslets = n_lenslets^2).

    pitch : float
        Center-to-center spacing of lenslets [m]. Also used as the
        square aperture of each lenslet.

    focal_length : float
        Focal length of each lenslet [m]. Positive = converging.

    wavelength : float
        Optical wavelength [m].

    Returns
    -------
    mla_mask : ndarray (complex, NxN)
        MLA transmission function (phase-only, unit amplitude within
        each lenslet aperture, no phase outside).
    """
    k = 2 * np.pi / wavelength
    x = (np.arange(N) - N / 2) * dx
    X, Y = np.meshgrid(x, x)

    # Fully vectorized MLA phase computation.
    #
    # Because the lenslets tile the plane periodically, every grid point
    # inside the MLA footprint can be snapped to its nearest lenslet
    # center in closed form:
    #
    #     j_nearest = clip(round(X/pitch + (n-1)/2), 0, n-1)
    #     xc        = (j_nearest - (n-1)/2) * pitch
    #
    # Then the local lens coordinate is dX = X - xc, and the lenslet
    # phase is -k/(2f) * (dX^2 + dY^2).  Outside the MLA footprint the
    # phase is left as zero.  This avoids the per-lenslet double loop
    # and brings the cost down from O(N^2 * K^2) to O(N^2) operations.
    half_extent = n_lenslets * pitch / 2
    in_mla = (np.abs(X) < half_extent) & (np.abs(Y) < half_extent)

    jx = np.clip(
        np.round(X / pitch + (n_lenslets - 1) / 2), 0, n_lenslets - 1
    )
    jy = np.clip(
        np.round(Y / pitch + (n_lenslets - 1) / 2), 0, n_lenslets - 1
    )
    xc = (jx - (n_lenslets - 1) / 2) * pitch
    yc = (jy - (n_lenslets - 1) / 2) * pitch

    dX = X - xc
    dY = Y - yc
    r_sq = dX * dX + dY * dY
    phase = np.where(in_mla, -k / (2 * focal_length) * r_sq, 0.0)

    return np.exp(1j * phase)


# ============================================================================
# Diffractive lenses (4.3.0)
# ============================================================================

def create_diffractive_lens(
    N: int,
    dx: float,
    focal_length: float,
    wavelength: float,
    *,
    center: Tuple[float, float] = (0.0, 0.0),
) -> np.ndarray:
    """Continuous-phase diffractive lens.

    Returns a phase-only transmission function ``exp(-i k r^2 / (2 f))``
    with ``k = 2 pi / lambda``, equivalent to the limiting case of a
    kinoform with infinite phase levels and to an ideal thin lens at
    the design wavelength.  Primary use is pedagogical and as a
    reference for :func:`create_kinoform` and
    :func:`create_fresnel_zone_plate`.

    Parameters
    ----------
    N : int
        Grid size (N x N).
    dx : float
        Grid spacing [m].
    focal_length : float
        Design focal length [m].  Positive = converging.
    wavelength : float
        Design wavelength [m].
    center : tuple of float, default (0.0, 0.0)
        Lens center offset from the grid center, ``(xc, yc)`` in metres.

    Returns
    -------
    T : ndarray (complex, N x N)
        Phase-only transmission function (``|T| = 1`` everywhere).

    See Also
    --------
    create_kinoform : multi-level quantized version of this lens.
    create_fresnel_zone_plate : binary amplitude or phase zone plate.
    apply_thin_lens : applies the same phase directly to a field.

    Notes
    -----
    Prior to 4.7 the kwargs were ``dx_m`` / ``focal_length_m`` /
    ``wavelength_m``.  4.7 dropped the ``_m`` suffix to match the
    rest of the library; LumenAiry uses SI metres throughout so the
    suffix was redundant.

    Examples
    --------
    >>> import lumenairy as la
    >>> T = la.create_diffractive_lens(N=256, dx=10e-6,
    ...                                  focal_length=50e-3,
    ...                                  wavelength=1.31e-6)
    >>> E_focused = E_plane_wave * T   # ready to propagate to z=f
    """
    if focal_length == 0:
        raise ValueError("focal_length must be non-zero")
    if N <= 0:
        raise ValueError(f"N must be > 0; got {N}")
    if dx <= 0:
        raise ValueError(f"dx must be > 0; got {dx}")
    if wavelength <= 0:
        raise ValueError(f"wavelength must be > 0; got {wavelength}")
    xc, yc = float(center[0]), float(center[1])
    x = (np.arange(N) - N / 2) * dx - xc
    y = (np.arange(N) - N / 2) * dx - yc
    X, Y = np.meshgrid(x, y)
    r2 = X * X + Y * Y
    k = 2.0 * np.pi / wavelength
    phase = -k * r2 / (2.0 * focal_length)
    return np.exp(1j * phase)


def create_kinoform(
    N: int,
    dx: float,
    focal_length: float,
    wavelength: float,
    *,
    n_levels: int = 8,
    center: Tuple[float, float] = (0.0, 0.0),
) -> np.ndarray:
    """Multi-level quantized phase diffractive lens (kinoform).

    Quantizes the continuous thin-lens phase ``phi(r) = -k r^2 / (2 f)``
    (mod 2 pi) to ``n_levels`` evenly-spaced phase steps in
    ``[0, 2 pi)``.  This is the canonical model of an etched phase
    grating, a multilevel diffractive lens, or an SLM driving a
    discretised phase profile.

    The first-order diffraction efficiency of an ideal kinoform is
    ``eta_1 = sinc^2(1 / n_levels)`` (~40.5% at 2 levels, ~81% at 4
    levels, ~95% at 8 levels, ~99% at 16 levels); the remaining power
    appears in higher diffraction orders.

    Parameters
    ----------
    N : int
        Grid size (N x N).
    dx : float
        Grid spacing [m].
    focal_length : float
        Design focal length [m].  Positive = converging.
    wavelength : float
        Design wavelength [m].
    n_levels : int, default 8
        Number of evenly-spaced phase levels in ``[0, 2 pi)``.  Must be
        >= 2.  ``n_levels = 2`` gives a binary phase Fresnel zone plate
        (equivalent to ``create_fresnel_zone_plate(binary=False)``);
        ``n_levels -> inf`` recovers the continuous diffractive lens.
    center : tuple of float, default (0.0, 0.0)
        Lens center offset from the grid center, ``(xc, yc)`` in metres.

    Returns
    -------
    T : ndarray (complex, N x N)
        Phase-only transmission function (``|T| = 1`` everywhere) with
        phase values quantized to one of ``n_levels`` discrete steps.

    See Also
    --------
    create_diffractive_lens : continuous-phase limit
        (``n_levels -> inf``).
    create_fresnel_zone_plate : binary amplitude or 2-level phase
        zone plate.

    Notes
    -----
    4.7 dropped the ``_m`` suffix from ``dx`` / ``focal_length`` /
    ``wavelength`` -- LumenAiry uses SI metres throughout, so the
    suffix was redundant.
    """
    if int(n_levels) < 2:
        raise ValueError(f"n_levels must be >= 2; got {n_levels}")
    if focal_length == 0:
        raise ValueError("focal_length must be non-zero")
    if N <= 0 or dx <= 0 or wavelength <= 0:
        raise ValueError("N, dx, wavelength must be > 0")
    xc, yc = float(center[0]), float(center[1])
    x = (np.arange(N) - N / 2) * dx - xc
    y = (np.arange(N) - N / 2) * dx - yc
    X, Y = np.meshgrid(x, y)
    r2 = X * X + Y * Y
    k = 2.0 * np.pi / wavelength
    phi_continuous = -k * r2 / (2.0 * focal_length)
    phi_wrapped = np.mod(phi_continuous, 2.0 * np.pi)
    step = 2.0 * np.pi / float(n_levels)
    phi_q = np.floor(phi_wrapped / step) * step
    return np.exp(1j * phi_q)


def create_fresnel_zone_plate(
    N: int,
    dx: float,
    focal_length: float,
    wavelength: float,
    *,
    binary: bool = True,
    n_zones: Optional[int] = None,
    center: Tuple[float, float] = (0.0, 0.0),
) -> np.ndarray:
    """Fresnel zone plate -- binary amplitude or binary phase.

    A Fresnel zone plate focuses light to ``focal_length`` via
    diffraction from concentric zones.  Zone boundaries are defined by
    half-wave phase jumps in the equivalent thin-lens phase
    ``phi(r) = -k r^2 / (2 f)``: zone ``n`` covers
    ``n lambda f <= r^2 < (n+1) lambda f`` (paraxial).

    Parameters
    ----------
    N : int
        Grid size (N x N).
    dx : float
        Grid spacing [m].
    focal_length : float
        Design focal length [m].  Positive = converging zone plate.
    wavelength : float
        Design wavelength [m].
    binary : bool, default True
        If True (default): amplitude FZP -- alternating zones
        transmit (1) or block (0).  First-order efficiency
        ``~1 / pi^2 ~= 10%`` at the design focus.

        If False: phase FZP (Rayleigh-Wood zone plate) -- alternating
        zones receive ``0`` or ``pi`` of phase, magnitude is unity
        everywhere.  First-order efficiency
        ``4 / pi^2 ~= 40%`` (~4x the amplitude case).
    n_zones : int, optional
        Number of zones to retain.  ``None`` (default) extends the
        zones out to the grid edge.  When provided, outside the
        n-th zone the transmission is 0 (the FZP has a finite outer
        aperture at ``r_n = sqrt(n lambda f)``).
    center : tuple of float, default (0.0, 0.0)
        Lens center offset from the grid center, ``(xc, yc)`` in metres.

    Returns
    -------
    T : ndarray (complex, N x N)
        Transmission function.  Binary amplitude: ``|T|`` is 0 or 1,
        phase 0 inside.  Binary phase: ``|T| = 1`` inside, phase 0
        or ``pi``.  Outside ``n_zones`` (when specified) ``T = 0``.

    See Also
    --------
    create_kinoform : multi-level quantized phase lens.
    create_diffractive_lens : continuous-phase diffractive lens.

    Notes
    -----
    The zone assignment uses ``zone_index = floor(r^2 / (lambda f))``,
    which aligns exactly with the phase-flip boundaries of an ideal
    converging quadratic phase.

    4.7 dropped the historical ``_m`` suffix from ``dx`` /
    ``focal_length`` / ``wavelength``.
    """
    if focal_length == 0:
        raise ValueError("focal_length must be non-zero")
    if N <= 0 or dx <= 0 or wavelength <= 0:
        raise ValueError("N, dx, wavelength must be > 0")
    if n_zones is not None and int(n_zones) < 1:
        raise ValueError(f"n_zones must be >= 1; got {n_zones}")

    xc, yc = float(center[0]), float(center[1])
    x = (np.arange(N) - N / 2) * dx - xc
    y = (np.arange(N) - N / 2) * dx - yc
    X, Y = np.meshgrid(x, y)
    r2 = X * X + Y * Y

    # 4.10: enforce positive focal length so the zone-plate behaves
    # as the docstring says ("Positive = converging").  Negative
    # focal_length used to silently strip the sign and produce an
    # identical converging FZP; users wanting a diverging FZP can flip
    # the sign of the applied phase elsewhere.
    if focal_length <= 0:
        raise ValueError(
            f"create_fresnel_zone_plate: focal_length must be > 0 "
            f"(got {focal_length}).  For a diverging zone plate, apply "
            f"a negative-sign phase to the converging FZP output.")
    lam_f = wavelength * focal_length
    zone_index = np.floor(r2 / lam_f).astype(int)

    if n_zones is not None:
        inside = zone_index < int(n_zones)
    else:
        inside = np.ones_like(zone_index, dtype=bool)

    is_even = (zone_index % 2 == 0)
    if binary:
        T = np.where(is_even & inside, 1.0 + 0j, 0.0 + 0j)
    else:
        phase = np.where(is_even, 0.0, np.pi)
        T = np.exp(1j * phase)
        if n_zones is not None:
            T = np.where(inside, T, 0.0 + 0j)
    return T


# ============================================================================
# Dammann grating design (IFTA)
# ============================================================================

def makedammann2d(
    periodx: float = 61e-6,
    periody: float = 61e-6,
    waveln: float = 1.31e-6,
    wavsamp: float = 0.5,
    phaselevels: int = 8,
    phasesteps: int = 4,
    diforders: Optional[np.ndarray] = None,
    diffractionthr: float = 0.25,
    nfmov: float = 0.5,
    itr: int = 3000,
    plot: bool = True,
    plot_every: int = 50,
    seed: Optional[int] = None,
    save_path: Optional[str] = None,
    cell_pixels: Optional[Union[int, Tuple[int, int]]] = None,
    _legacy_units: str = 'SI',
) -> Tuple[np.ndarray, np.ndarray, Tuple[float, float]]:
    """
    Design a 2D Dammann grating using an iterative Fourier transform algorithm.

    Uses an IFTA (Iterative Fourier Transform Algorithm) to find a phase-only
    near-field distribution whose Fourier transform produces a uniform array
    of diffraction orders.  Phase quantisation is progressively tightened over
    the iterations (simulated-annealing style).

    .. versionchanged:: 4.14.2
        Units are now SI metres throughout (was micrometres).  ``periodx``,
        ``periody`` and ``waveln`` are expected in **metres**; the returned
        ``cell_pixel_size`` is in metres and matches them directly (no
        internal ``* 1e-6`` rescale).  Pre-4.14.2 callers passing
        ``periodx=61.0`` / ``waveln=1.31`` (micrometres) hit a thousand-
        fold drift in ``samplingx`` that was silently masked by an
        output ``* 1e-6`` rescale.  v4.14.2 emits a ``DeprecationWarning``
        when ``periodx``, ``periody`` or ``waveln`` look like micrometres
        (heuristic: ``periodx > 1e-3 m`` or ``waveln > 1e-3 m``, i.e.
        larger than 1 mm) and treats the inputs as legacy micrometre
        values; remove the warning by converting your call sites to SI
        (multiply old values by ``1e-6``).

    .. versionchanged:: 4.14.3
        The ``> 1e-3`` legacy-um heuristic silently miscompiled THz / MMW
        designs where SI-correct ``periodx`` / ``waveln`` legitimately
        exceed 1 mm (e.g. 5 mm grating period at 1.1 mm far-IR
        wavelength).  Two guards added: (1) inputs above 1 m are
        rejected as unambiguously wrong (``ValueError``); (2) an
        explicit ``_legacy_units`` kwarg (``'auto'`` / ``'um'`` /
        ``'SI'``) lets THz / MMW users bypass the heuristic.  Pass
        ``_legacy_units='SI'`` to opt out of the auto rescale and
        accept mm-scale inputs as SI metres.  Supported wavelength
        range: 10 nm (``1e-8 m``) -- 1 mm (``1e-3 m``) under the
        ``'auto'`` mode; up to 1 m under ``'SI'`` mode.

    .. versionchanged:: 5.30
        ``_legacy_units`` default flipped ``'auto'`` -> ``'SI'`` **and the
        micrometre auto-detect mode was removed entirely** (audit E-H11,
        ``AUDIT_ADVERSARIAL_CODEBASE_2026_07_25``, executed in the W5
        shim-removal wave).  The ``'auto'`` heuristic silently multiplied
        any ``periodx`` / ``periody`` / ``waveln`` above 1 mm by ``1e-6``,
        so a physically correct SI THz / MMW design (8 mm period at 1.1 mm
        wavelength) came back with 5e-10 m cells -- a factor 1e-6 wrong --
        and the only diagnostic was a ``DeprecationWarning``, which is
        suppressed by default outside ``__main__``.  SI metres are now
        taken at face value: no rescale, no warning.  A shim that
        SILENTLY REWRITES physical inputs cannot be left reachable once
        it is known wrong for a legitimate design regime, so ``'auto'``
        was retired rather than given another cycle: passing
        ``_legacy_units='auto'`` now raises ``ValueError`` naming the two
        surviving modes.  Explicit ``_legacy_units='um'`` is unchanged and
        is the supported migration path for genuine micrometre call
        sites: ``'auto'``'s per-parameter rescale is reproduced exactly by
        ``'um'`` whenever every parameter was micrometre-valued (its own
        documented use case), and a hybrid call must state which values
        are which rather than have a magnitude heuristic guess.

    Parameters
    ----------
    periodx : float
        Grating period in x [m].  Default ``61e-6`` (61 um).
    periody : float
        Grating period in y [m].  Default ``61e-6`` (61 um).
    waveln : float
        Design wavelength [m].  Default ``1.31e-6`` (1.31 um, telecom
        O-band).
    wavsamp : float
        Spatial sampling expressed in wavelengths (e.g. 0.5 -> half-wavelength).
    phaselevels : int
        Number of quantised phase levels in the final grating.
    phasesteps : int
        Annealing schedule exponent -- controls how quickly phase quantisation
        tightens over iterations.
    diforders : np.ndarray or None
        2-D array specifying the target diffraction-order pattern (amplitudes).
        ``None`` defaults to ``np.ones((12, 12))``.
    diffractionthr : float
        Intensity threshold used to identify "active" orders when computing
        uniformity and efficiency metrics.
    nfmov : float
        Near-field blending / momentum factor (0-1).  Smaller values make
        early iterations more conservative.
    itr : int
        Total number of IFTA iterations.
    plot : bool
        If True, display progress plots every *plot_every* iterations and at
        completion.
    plot_every : int
        Plotting cadence (iterations between plot updates).
    seed : int or None
        Random seed for reproducibility.  ``None`` leaves the RNG unseeded.
    save_path : str or None
        If provided, save the final quantized phase (radians) to this file
        in CSV format compatible with :func:`load_phase_file`.
    cell_pixels : int, (int, int), or None, default ``None``
        Force the unit-cell pixel count directly, overriding the
        ``wavsamp``-derived grid size.  ``None`` (default) keeps the
        historical behaviour: the cell is
        ``ndifordersx = ceil(periodx / (wavsamp * waveln) * 0.5) * 2``
        pixels wide (and similarly in y).  An ``int`` sets both axes to
        that many pixels; a ``(nx, ny)`` tuple sets them independently.

        The primary use is **grid-native DOE design**: choose
        ``cell_pixels = round(period / dx_grid)`` so the returned
        ``cell_pixel_size`` equals your propagation grid spacing
        ``dx_grid`` *exactly* and the cell tiles an integer number of
        grid pixels.  :func:`create_periodic_phase_mask` then maps one
        cell pixel to one grid pixel (no nearest-neighbour resample), so
        the phase transitions land on grid lines and no power is
        scattered out of the design orders by sampling jitter.  Each
        count must be even (the annealing / order-embedding logic uses
        ``n // 2``) and at least as large as the corresponding
        ``diforders`` dimension.
    _legacy_units : {'SI', 'um'}, default ``'SI'``
        Unit system of ``periodx`` / ``periody`` / ``waveln``.

        - ``'SI'`` (default since v5.30): the inputs are SI metres,
          unconditionally -- no rescale, no warning, even if values
          exceed 1 mm.  This is correct for THz / MMW designs where
          ``periodx=5e-3`` (5 mm) and ``waveln=1.1e-3`` (1.1 mm
          far-IR) are physically meaningful.
        - ``'um'``: the inputs are interpreted as legacy micrometres
          unconditionally -- each value is multiplied by ``1e-6``.
          No warning is emitted (the caller stated the convention).
          This is the supported migration path for call sites that
          still hold micrometre values.

        ``'auto'`` (the v4.14.2 per-parameter ">1 mm means micrometres"
        heuristic) was **removed in v5.30** and raises ``ValueError``.
        It was the default up to v5.29, where it silently miscompiled
        every SI THz / MMW design.

        In ``'SI'`` mode, inputs above 1 m are rejected as unambiguously
        wrong -- a metre-scale grating period or design wavelength is
        nonsense.  ``'um'`` mode has no upper bound on the raw input (the
        caller stated micrometres) and its rescaled result is not bounded
        either, matching the prior behaviour.

    Returns
    -------
    nearfield : np.ndarray (complex)
        Final near-field distribution (phase-only, quantized to phaselevels).
    farfield : np.ndarray (complex)
        Far-field (Fourier plane) distribution at the last iteration.
    cell_pixel_size : tuple of (float, float)
        Physical pixel spacing ``(dx, dy)`` of the near-field array [m].
        For square gratings (``periodx == periody``), both values are equal.

    Examples
    --------
    >>> # Default 12x12 spot array at 1.31 um -- SI metres throughout
    >>> nf, ff, cell_dx = makedammann2d(plot=False)
    >>>
    >>> # Custom 8x8 array, visible wavelength, fewer phase levels
    >>> nf, ff, cell_dx = makedammann2d(
    ...     periodx=80e-6, periody=80e-6, waveln=633e-9,
    ...     diforders=np.ones((8, 8)),
    ...     phaselevels=4, itr=1000, plot=False, seed=42,
    ... )

    Notes
    -----
    Ported to Python by Andrew Traverso from the original Octave/MATLAB
    implementation (makedammann2d.m) by Daniel Marks.
    """
    from numpy.fft import fft2, fftshift, ifft2, ifftshift

    # v4.14.3: dispatch on ``_legacy_units``.  Two modes (v5.30):
    #
    #   'SI'   -- pass-through, accept mm-scale inputs as SI metres
    #             (intended for THz / MMW designs).  DEFAULT since
    #             v5.30 (audit E-H11).
    #   'um'   -- explicit legacy micrometres; rescale unconditionally
    #             with NO warning.
    #
    # v5.30 (W5 shim-removal wave): the v4.14.2 ``'auto'`` heuristic is
    # REMOVED.  It rescaled by 1e-6 whenever a value exceeded 1 mm, which
    # is exactly wrong for a physical THz / MMW design; retiring it to an
    # explicit opt-in (v5.30 audit E-H11) was the first step, deleting it
    # the second.  A shim that silently rewrites physical inputs is not
    # given another cycle.  Precedent for the explicit named rejection:
    # ``propagators/system.py`` ``_reject_legacy`` (v5.0 aperture schema)
    # -- the mode name INTERCEPTED VALUES, so a bare "not valid" message
    # would leave a migrating caller without the recipe.
    if _legacy_units == 'auto':
        raise ValueError(
            "makedammann2d: _legacy_units='auto' was REMOVED in v5.30.  "
            "The v4.14.2 heuristic rescaled any periodx / periody / "
            "waveln above 1 mm by 1e-6, which silently miscompiled every "
            "physically-correct SI THz / MMW design (an 8 mm period at "
            "1.1 mm wavelength came back with 5e-10 m cells).  Migrate: "
            "pass SI metres and drop the kwarg entirely ('SI' is the "
            "default since v5.30), or pass _legacy_units='um' to convert "
            "micrometre-valued inputs explicitly (periodx=61.0, "
            "waveln=1.31 -> 61 um / 1.31 um).  Mixed-unit calls must be "
            "normalised by the caller -- no heuristic guesses which is "
            "which."
        )
    # Validate the mode here so a typo (e.g. ``_legacy_units='m'``)
    # fails fast rather than silently picking up a fallback.
    if _legacy_units not in ('um', 'SI'):
        raise ValueError(
            f"makedammann2d: _legacy_units={_legacy_units!r} is not "
            "valid; expected one of 'um', 'SI'."
        )

    # DOE-nit (AUDIT_DOE_GRATING_FREEFORM): validate the loop / sampling
    # counts.  ``itr < 1`` makes the annealing schedule
    # ``2**floor(phasesteps*(itr-it)/itr)`` a 0/0 -> ``int(nan)`` crash, and
    # ``wavsamp <= 0`` blows up ``ndifordersx = ceil(.../wavsamp)``.  Give an
    # actionable message instead of a deep-stack error.
    if int(itr) < 1:
        raise ValueError(
            f"makedammann2d: itr must be >= 1 (got {itr!r}); it sets the "
            "annealing iteration budget.")
    if not (wavsamp > 0):
        raise ValueError(
            f"makedammann2d: wavsamp must be > 0 (got {wavsamp!r}); it sets "
            "the wavelength/diffraction-order sampling density.")

    # v4.14.3 (P0-NEW-2 / Agent A A.2): unambiguous-nonsense upper
    # bound applies to ``'SI'`` mode.  A meter-scale grating period or
    # design wavelength is wrong under that interpretation.  Tests for
    # THz / MMW (mm-scale SI) designs depended on the ability to pass
    # ``periodx=5e-3``; the removed v4.14.2 ``'auto'`` heuristic
    # miscompiled those calls.  In ``'um'`` mode the caller explicitly
    # stated micrometres, so ``periodx=61.0`` (61 um) is a legitimate
    # value -- skip the upper bound there.
    def _reject_above_one_metre():
        if periodx > 1.0:
            raise ValueError(
                f"makedammann2d: periodx={periodx} m exceeds 1 m; "
                "if your input is in micrometres, the auto-detect form "
                "was REMOVED in v5.30 -- pass SI metres explicitly (e.g. "
                "``periodx=61e-6``) or set ``_legacy_units='um'``.  "
                "If your input is genuinely in metres, the value is "
                "physically implausible for a Dammann grating."
            )
        if periody > 1.0:
            raise ValueError(
                f"makedammann2d: periody={periody} m exceeds 1 m; "
                "if your input is in micrometres, the auto-detect form "
                "was REMOVED in v5.30 -- pass SI metres explicitly (e.g. "
                "``periody=61e-6``) or set ``_legacy_units='um'``.  "
                "If your input is genuinely in metres, the value is "
                "physically implausible for a Dammann grating."
            )
        if waveln > 1.0:
            raise ValueError(
                f"makedammann2d: waveln={waveln} m exceeds 1 m; "
                "if your input is in micrometres, the auto-detect form "
                "was REMOVED in v5.30 -- pass SI metres explicitly (e.g. "
                "``waveln=1.31e-6``) or set ``_legacy_units='um'``.  "
                "If your input is genuinely in metres, the value is "
                "physically implausible for a design wavelength."
            )

    if _legacy_units == 'um':
        # Explicit-legacy migration path.  Caller knows the inputs are
        # micrometres -- silent rescale with no warning.
        periodx = periodx * 1e-6
        periody = periody * 1e-6
        waveln = waveln * 1e-6
    else:
        # Explicit SI metres (the default).  Pass through unchanged --
        # this is the THz / MMW escape hatch.
        _reject_above_one_metre()

    if diforders is None:
        diforders = np.ones((12, 12))
    diforders = np.asarray(diforders, dtype=float)

    # 4.12.0 (B1-11): use a local Generator (np.random.default_rng)
    # instead of seeding the global ``np.random`` state.  Pre-4.12.0
    # the call ``np.random.seed(seed)`` perturbed the user's process-
    # wide RNG state -- a high-severity library anti-pattern, since
    # any other code in the same Python session that depended on
    # legacy ``np.random`` reproducibility silently lost it after a
    # ``makedammann2d`` call.  The local generator gives the same
    # bit-for-bit output for a given ``seed=`` while leaving the
    # global RNG untouched.
    rng = np.random.default_rng(seed)

    # -- Grid sizing -------------------------------------------------------
    ndifordersx = int(np.ceil(periodx / (wavsamp * waveln) * 0.5)) * 2
    ndifordersy = int(np.ceil(periody / (wavsamp * waveln) * 0.5)) * 2

    # Grid-native override: pin the cell pixel count directly so the
    # returned cell_pixel_size == the caller's propagation grid dx and the
    # cell tiles an integer number of grid pixels (lossless 1:1 mapping in
    # create_periodic_phase_mask).  See the ``cell_pixels`` docstring.
    if cell_pixels is not None:
        if np.isscalar(cell_pixels):
            _cpx = _cpy = int(cell_pixels)
        else:
            _cpx, _cpy = (int(v) for v in cell_pixels)
        for _lbl, _cp, _nord in (('x', _cpx, diforders.shape[0]),
                                 ('y', _cpy, diforders.shape[1])):
            if _cp < 2 or _cp % 2 != 0:
                raise ValueError(
                    f"makedammann2d: cell_pixels[{_lbl}]={_cp} must be an "
                    "even integer >= 2 (the annealing / order-embedding "
                    "logic indexes with n // 2).")
            if _cp < _nord:
                raise ValueError(
                    f"makedammann2d: cell_pixels[{_lbl}]={_cp} is smaller "
                    f"than the target order count ({_nord}); the cell cannot "
                    "hold the requested diffraction orders.")
        ndifordersx = _cpx
        ndifordersy = _cpy

    samplingx = periodx / ndifordersx
    samplingy = periody / ndifordersy

    # -- Target diffraction order pattern ----------------------------------
    # Symmetric centred placement: without this the port from the
    # Octave code's 1-based ``ceil((N - n) / 2) + 1`` fell into an
    # off-by-one when ``(N - n)`` was odd, placing the input pattern
    # one cell to the left of centre.  That broke the binary symmetry
    # Dammann designs depend on.  Plain integer division gives a
    # symmetric embedding in both parities.
    totaldiforders = np.zeros((ndifordersx, ndifordersy))
    x0 = (ndifordersx - diforders.shape[0]) // 2
    y0 = (ndifordersy - diforders.shape[1]) // 2
    totaldiforders[x0:x0 + diforders.shape[0], y0:y0 + diforders.shape[1]] = diforders

    # Axis vectors for plotting
    diforderx_ax = np.arange(-ndifordersx // 2, ndifordersx // 2)
    difordery_ax = np.arange(-ndifordersy // 2, ndifordersy // 2)
    rxscal = (np.arange(-ndifordersx // 2 + 0.5, ndifordersx // 2 - 0.5 + 1e-9)) * samplingx
    ryscal = (np.arange(-ndifordersy // 2 + 0.5, ndifordersy // 2 - 0.5 + 1e-9)) * samplingy

    # -- Initial near-field (separable random phase) -----------------------
    phsx, phsy = np.meshgrid(
        rng.random(ndifordersx),
        rng.random(ndifordersy),
        indexing='ij',
    )
    nearfield = np.exp(2j * np.pi * (phsx + phsy) - 1j * np.pi)

    # -- Iteration ---------------------------------------------------------
    totaldifnorm = (np.sum(np.abs(totaldiforders) ** 2) / totaldiforders.size) ** 0.5

    farfieldamp = None
    farfield = None

    if plot:
        import matplotlib.pyplot as plt
        plt.ion()
        fig, axes = plt.subplots(1, 3, figsize=(15, 4))

    nfmov_cur = nfmov

    for it in range(itr + 1):
        phaselevelscur = phaselevels * 2 ** int(np.floor(phasesteps * (itr - it) / itr))

        if it == itr:
            nfmov_cur = 0

        # Forward transform (near field -> far field)
        farfield = fftshift(fft2(fftshift(nearfield))) / np.sqrt(nearfield.size)

        # Amplitude replacement in the far field
        if it == 0:
            farfieldamp = totaldiforders.copy()
        else:
            farfieldamp = 0.00001 + (farfieldamp / np.abs(farfield)) * totaldiforders

        # Normalise far-field amplitude
        farfieldamp = farfieldamp * totaldifnorm / np.sqrt(
            np.sum(farfieldamp ** 2) / farfieldamp.size
        )

        # Combine amplitude constraint with current phase.
        #
        # Audit P2-07 (post-v5.17.0): this used ``np.sign(farfield)``,
        # which is only the Octave ``sign()`` (= z/|z|) this port needs
        # on NumPy >= 2.0.  On NumPy 1.x complex ``np.sign`` returned
        # ``sign(z.real)`` (falling back to ``sign(z.imag)`` on the
        # imaginary axis), so the far-field phase was replaced by +-1
        # each iteration and the IFTA silently degenerated (8x8
        # target, itr=200: uniformity 0.97 -> 0.00).
        #
        # v5.38: ``numpy>=2.0`` is now the packaged floor, so that
        # hazard is EXCLUDED rather than defended against.  The explicit
        # unit phasor stays because it is what the port means -- z/|z|,
        # 0-safe (0 -> 0, matching ``np.sign(0) == 0``) -- and it is
        # bit-identical to NumPy 2.x complex ``np.sign`` (A/B verified),
        # so nothing about the shipped answer depends on the choice.
        _ff_mag = np.hypot(farfield.real, farfield.imag)
        _ff_unit = np.zeros_like(farfield)
        np.divide(farfield.real, _ff_mag, out=_ff_unit.real,
                  where=_ff_mag > 0)
        np.divide(farfield.imag, _ff_mag, out=_ff_unit.imag,
                  where=_ff_mag > 0)
        farfield2 = farfieldamp * _ff_unit

        # Inverse transform (far field -> near field)
        nearfield2 = ifftshift(ifft2(ifftshift(farfield2))) * np.sqrt(farfield2.size)

        # Quantise phase
        phs = (
            np.floor(0.5 + np.angle(nearfield2) * (phaselevelscur / (2 * np.pi)))
            * (2 * np.pi / phaselevelscur)
        )

        # Blending / momentum update
        nfmovitr = nfmov_cur + (1.0 - nfmov_cur) * (it / itr)
        nearfield = (1 - nfmovitr) * nearfield + nfmovitr * (totaldifnorm * np.exp(1j * phs))

        # -- Plotting ------------------------------------------------------
        if plot and (it % plot_every == 0 or it == itr):
            for ax in axes:
                ax.clear()

            # v4.14.2: ``rxscal``/``ryscal`` are now in SI metres
            # (post-SI conversion); scale to micrometres for display
            # so the plot axes match the historical user expectation.
            _um = 1e6
            axes[0].imshow(
                np.angle(nearfield).T,
                extent=[rxscal[0] * _um, rxscal[-1] * _um,
                        ryscal[-1] * _um, ryscal[0] * _um],
                aspect='auto',
            )
            axes[0].set_title(f'Phase Levels {phaselevelscur}')
            axes[0].set_xlabel('Distance (um)')
            axes[0].set_ylabel('Distance (um)')

            axes[1].imshow(
                np.abs(nearfield).T,
                extent=[rxscal[0] * _um, rxscal[-1] * _um,
                        ryscal[-1] * _um, ryscal[0] * _um],
                aspect='auto',
            )
            axes[1].set_title('Absolute value')
            axes[1].set_xlabel('Distance (um)')
            axes[1].set_ylabel('Distance (um)')

            diffrac = np.abs(farfield) ** 2
            active = diffrac[diffrac > diffractionthr]
            if active.size > 0:
                ratiodif = active.min() / active.max()
                efficiencydif = active.sum() / diffrac.sum()
            else:
                ratiodif = 0.0
                efficiencydif = 0.0

            axes[2].imshow(
                diffrac.T,
                extent=[diforderx_ax[0], diforderx_ax[-1], difordery_ax[-1], difordery_ax[0]],
                aspect='auto',
            )
            axes[2].set_title(
                f'Diffractive power {ratiodif:.4g} ratio, {efficiencydif:.4g} efficiency'
            )
            axes[2].set_xlabel('Diffraction order')
            axes[2].set_ylabel('Diffraction order')

            fig.tight_layout()
            plt.pause(0.25)

    # Final quantization to target phase levels (not binary)
    final_phase = (
        np.floor(0.5 + np.angle(nearfield) * (phaselevels / (2 * np.pi)))
        * (2 * np.pi / phaselevels)
    )
    nearfield = np.exp(1j * final_phase)

    # Physical pixel size [m] -- v4.14.2 (P1-NEW-6): the internal math
    # now operates in SI metres end-to-end (``periodx``/``periody`` are
    # the SI inputs after the legacy-um normalisation above), so
    # ``samplingx`` already carries the metre unit and the legacy
    # ``* 1e-6`` um->m rescale is gone.
    cell_pixel_size_x = samplingx
    cell_pixel_size_y = samplingy
    cell_pixel_size = cell_pixel_size_x  # for square gratings; both returned below

    # Save to file if requested
    if save_path is not None:
        # ``cell_pixel_size`` is already in SI metres; ``save_phase_file``
        # handles the um conversion for human-readable header lines.
        # Metadata records the *period* and *wavelength* in micrometres
        # for backward-compatibility with older readers that expected
        # the ``_um`` suffix.
        save_phase_file(save_path, final_phase, cell_pixel_size=cell_pixel_size,
                        metadata={
                            'phaselevels': phaselevels,
                            'periodx_um': periodx * 1e6,
                            'periody_um': periody * 1e6,
                            'wavelength_um': waveln * 1e6,
                            'diforders': f'{diforders.shape[0]}x{diforders.shape[1]}',
                        })

    if plot:
        plt.ioff()
        plt.show()

    return nearfield, farfield, (cell_pixel_size_x, cell_pixel_size_y)


# =============================================================================
# FITS FILE I/O (optional — requires astropy)
# =============================================================================

import importlib.util as _importlib_util

_ASTROPY_AVAILABLE = _importlib_util.find_spec('astropy') is not None
_fits = None  # populated lazily by _ensure_astropy_loaded()


def _ensure_astropy_loaded():
    global _fits
    if _fits is None and _ASTROPY_AVAILABLE:
        from astropy.io import fits as _f
        _fits = _f
    return _fits is not None


def load_fits_field(
    filepath: str,
    hdu_amplitude: int = 0,
    hdu_phase: Optional[int] = None,
) -> Tuple[np.ndarray, Dict[str, Any]]:
    """
    Load a complex optical field from a FITS file.

    Supports two common formats:
    - Two HDUs: amplitude in one HDU, phase in another
    - Single HDU with complex data or [real, imag] stack along first axis

    Parameters
    ----------
    filepath : str
        Path to the .fits file.
    hdu_amplitude : int, default 0
        HDU index for the amplitude array (or complex array if hdu_phase is None).
    hdu_phase : int or None, default None
        HDU index for the phase array [radians]. If None, ``hdu_amplitude``
        is assumed to contain either complex data or a [real, imag] stack.

    Returns
    -------
    E : ndarray (complex, N×N)
        Complex field.
    metadata : dict
        Selected header keywords (wavelength, dx, dy) if present.

    Notes
    -----
    Requires the ``astropy`` package. Install via ``pip install astropy``.
    """
    if not _ASTROPY_AVAILABLE:
        raise ImportError("astropy is required for FITS support. "
                          "Install with: pip install astropy")
    _ensure_astropy_loaded()

    with _fits.open(filepath) as hdul:
        amp_data = np.array(hdul[hdu_amplitude].data)
        header = dict(hdul[hdu_amplitude].header)

        if hdu_phase is not None:
            phase_data = np.array(hdul[hdu_phase].data)
            E = amp_data * np.exp(1j * phase_data)
        elif amp_data.ndim == 3 and amp_data.shape[0] == 2:
            E = amp_data[0] + 1j * amp_data[1]
        elif np.iscomplexobj(amp_data):
            E = amp_data.astype(complex)
        else:
            # DOE-1 (AUDIT_DOE_GRATING_FREEFORM): auto-detect the SPLIT
            # amp/phase layout -- which is the DEFAULT of
            # ``save_fits_field`` (2-D real amplitude primary + a second HDU
            # tagged ``EXTNAME='PHASE'`` / ``BUNIT='radians'``).  Pre-fix the
            # default save -> default load (``hdu_phase=None``) round-trip
            # took this "amplitude only" branch and SILENTLY dropped all
            # phase (mirroring the real/imag-stack auto-detection above).
            _phase_hdu = None
            for _h in hdul[1:]:
                _hdr = _h.header
                if (str(_hdr.get('EXTNAME', '')).upper() == 'PHASE'
                        or str(_hdr.get('BUNIT', '')).lower() == 'radians'):
                    _phase_hdu = _h
                    break
            if _phase_hdu is not None and _phase_hdu.data is not None:
                phase_data = np.array(_phase_hdu.data)
                E = amp_data * np.exp(1j * phase_data)
            else:
                # Genuinely amplitude-only -- assume zero phase.
                E = amp_data.astype(complex)

    # DOE-nit (AUDIT_DOE_GRATING_FREEFORM): fall back to PIXSCALE only when
    # the specific key is ABSENT -- an explicit ``DX == 0.0`` (odd but
    # possible) should be taken literally, not treated as falsy and
    # overridden by PIXSCALE.
    _dx = header.get('DX')
    _dx = header.get('PIXSCALE') if _dx is None else _dx
    _dy = header.get('DY')
    _dy = header.get('PIXSCALE') if _dy is None else _dy
    metadata = {
        'wavelength': header.get('WAVELENG'),
        'dx': _dx,
        'dy': _dy,
    }
    return E, metadata


def save_fits_field(
    filepath: str,
    E: np.ndarray,
    wavelength: Optional[float] = None,
    dx: Optional[float] = None,
    dy: Optional[float] = None,
    metadata: Optional[Dict[str, Any]] = None,
    split_amp_phase: bool = True,
) -> None:
    """
    Save a complex optical field to a FITS file.

    Parameters
    ----------
    filepath : str
        Output .fits path.
    E : ndarray (complex, N×N)
        Complex field to save.
    wavelength : float, optional
        Wavelength [m]. Stored as WAVELENG header keyword.
    dx, dy : float, optional
        Grid spacings [m]. Stored as DX, DY header keywords.
    metadata : dict, optional
        Additional header keywords to include.
    split_amp_phase : bool, default True
        If True, save as two HDUs (amplitude + phase).
        If False, save as a single 3D array [real, imag, ...].

    Notes
    -----
    Requires ``astropy``. The split format (default) is more widely
    compatible with standard astronomy tools.
    """
    if not _ASTROPY_AVAILABLE:
        raise ImportError("astropy is required for FITS support. "
                          "Install with: pip install astropy")
    _ensure_astropy_loaded()

    header = _fits.Header()
    if wavelength is not None:
        header['WAVELENG'] = (wavelength, 'Wavelength [m]')
    if dx is not None:
        header['DX'] = (dx, 'Grid spacing in x [m]')
    if dy is not None:
        header['DY'] = (dy, 'Grid spacing in y [m]')
    if metadata:
        # DOE-nit (AUDIT_DOE_GRATING_FREEFORM): FITS keywords are capped at 8
        # chars, so two metadata keys sharing an 8-char prefix would silently
        # collapse into one card (the later value overwrites the earlier).
        # Warn on collision rather than lose data silently.
        _seen_cards: Dict[str, str] = {}
        for key, value in metadata.items():
            card = key.upper()[:8]
            if card in _seen_cards and _seen_cards[card] != key:
                warnings.warn(
                    f"save_fits_field: metadata keys {_seen_cards[card]!r} "
                    f"and {key!r} both truncate to the 8-char FITS card "
                    f"{card!r}; the later value overwrites the earlier.  "
                    f"Rename one to keep both.",
                    UserWarning, stacklevel=2)
            _seen_cards[card] = key
            header[card] = value

    if split_amp_phase:
        amp = np.abs(E).astype(np.float32)
        phase = np.angle(E).astype(np.float32)

        primary = _fits.PrimaryHDU(amp, header=header)
        primary.header['EXTNAME'] = 'AMPLITUDE'

        phase_hdu = _fits.ImageHDU(phase)
        phase_hdu.header['EXTNAME'] = 'PHASE'
        phase_hdu.header['BUNIT'] = 'radians'

        _fits.HDUList([primary, phase_hdu]).writeto(filepath, overwrite=True)
    else:
        stacked = np.stack([np.real(E), np.imag(E)]).astype(np.float32)
        primary = _fits.PrimaryHDU(stacked, header=header)
        primary.header['FORMAT'] = 'real_imag_stack'
        primary.writeto(filepath, overwrite=True)
