"""
Diffractive optical element (DOE), grating, and phase mask functions.

This module provides tools for creating and manipulating phase-only
diffractive elements:

- **Periodic phase masks** -- tile a unit cell across a simulation grid
  using nearest-neighbor resampling.
- **Microlens arrays** -- generate the quadratic phase profile of a
  square-aperture MLA.
- **Dammann gratings** -- design uniform spot-array generators via an
  iterative Fourier transform algorithm (IFTA).
- **Phase file I/O** -- load and save phase arrays in a simple CSV
  format with optional metadata header.
- **FITS I/O** -- load and save complex fields in FITS format (requires
  the optional ``astropy`` dependency).

Author: Andrew Traverso
"""

import numpy as np


# ============================================================================
# Phase file I/O
# ============================================================================

def load_phase_file(filepath):
    """
    Load a DOE / grating phase profile from a CSV file.

    Reads a comma-separated file of phase values in radians.
    The file may have been generated by :func:`save_phase_file` or by
    an external tool (e.g. the Optopax 12x12 beam splitter .dat file).

    Parameters
    ----------
    filepath : str
        Path to the CSV file.

    Returns
    -------
    phase : ndarray (M×M or M×N)
        Phase in radians.
    """
    phase = np.genfromtxt(filepath, delimiter=',')
    if phase.ndim != 2:
        raise ValueError(f"Expected 2D phase array, got shape {phase.shape}")
    return phase


def save_phase_file(filepath, phase, cell_pixel_size=None, metadata=None):
    """
    Save a phase profile to a CSV file compatible with :func:`load_phase_file`.

    Writes phase values in radians as comma-separated values.
    Optionally prepends a comment header with cell pixel size and
    other metadata so the file is self-describing.

    Parameters
    ----------
    filepath : str
        Output file path (typically .dat or .csv).

    phase : ndarray (M×M)
        Phase in radians.

    cell_pixel_size : float, optional
        Native pixel spacing of the phase array [m]. If provided, written
        to the header so loaders know the physical scale.

    metadata : dict, optional
        Additional key-value pairs to include in the header comment.
        Example: {'phaselevels': 256, 'wavelength_um': 1.31}
    """
    header_lines = []
    if cell_pixel_size is not None:
        header_lines.append(f"cell_pixel_size_um={cell_pixel_size*1e6:.6f}")
        header_lines.append(f"cell_extent_um={phase.shape[0] * cell_pixel_size * 1e6:.3f}")
    header_lines.append(f"shape={phase.shape[0]}x{phase.shape[1]}")
    if metadata:
        for k, v in metadata.items():
            header_lines.append(f"{k}={v}")

    header = ', '.join(header_lines)
    np.savetxt(filepath, phase, delimiter=',', header=header, fmt='%.8f')


# ============================================================================
# Phase masks
# ============================================================================

def create_periodic_phase_mask(N, dx, phase_cell, cell_pixel_size):
    """
    Tile a periodic phase element (DOE, grating, etc.) across the simulation grid.

    The element is defined by a single unit cell with its own native pixel size.
    This function resamples it onto the simulation grid using nearest-neighbor
    mapping and tiles it periodically.

    Parameters
    ----------
    N : int
        Simulation grid size (NxN).

    dx : float
        Simulation grid spacing [m].

    phase_cell : ndarray (M×M)
        Phase of one unit cell in radians. The cell has M×M pixels at
        the native pixel spacing.

    cell_pixel_size : float
        Native pixel spacing of the phase cell [m].
        The unit cell extent is phase_cell.shape[0] * cell_pixel_size.

    Returns
    -------
    mask : ndarray (complex, NxN)
        Transmission function (unit amplitude, phase-only), periodically
        tiled across the full simulation grid.

    Notes
    -----
    When the simulation grid spacing dx is larger than cell_pixel_size,
    this performs a downsampling via nearest-neighbor. For smooth phase
    profiles (typical for far-field DOEs), this is adequate. For phase
    masks with sub-pixel features, consider pre-averaging the complex
    transmission exp(i*phase) over each simulation pixel.
    """
    cell_N = phase_cell.shape[0]
    cell_extent = cell_N * cell_pixel_size

    # Simulation grid coordinates (same axis for x and y on a square grid)
    coord = (np.arange(N) - N / 2) * dx

    # Map each sim coordinate into the unit cell (periodic tiling)
    in_cell = np.mod(coord, cell_extent)

    # Nearest-neighbor pixel index within the cell
    idx = np.clip((in_cell / cell_pixel_size).astype(int), 0, cell_N - 1)
    ix = idx
    iy = idx

    # Build 2D phase by indexing into the unit cell
    IX, IY = np.meshgrid(ix, iy)
    phase_tiled = phase_cell[IY, IX]

    return np.exp(1j * phase_tiled)


def create_microlens_array(N, dx, n_lenslets, pitch, focal_length, wavelength):
    """
    Create a microlens array (MLA) phase mask.

    Each lenslet is a thin converging lens (quadratic phase) centered on its
    array position, with a square aperture equal to the pitch. Lenslets do not
    overlap; each pixel on the grid belongs to exactly one lenslet.

    Parameters
    ----------
    N : int
        Simulation grid size (NxN).

    dx : float
        Grid spacing [m].

    n_lenslets : int
        Number of lenslets per side (total lenslets = n_lenslets^2).

    pitch : float
        Center-to-center spacing of lenslets [m]. Also used as the
        square aperture of each lenslet.

    focal_length : float
        Focal length of each lenslet [m]. Positive = converging.

    wavelength : float
        Optical wavelength [m].

    Returns
    -------
    mla_mask : ndarray (complex, NxN)
        MLA transmission function (phase-only, unit amplitude within
        each lenslet aperture, no phase outside).
    """
    k = 2 * np.pi / wavelength
    x = (np.arange(N) - N / 2) * dx
    X, Y = np.meshgrid(x, x)

    # Fully vectorized MLA phase computation.
    #
    # Because the lenslets tile the plane periodically, every grid point
    # inside the MLA footprint can be snapped to its nearest lenslet
    # center in closed form:
    #
    #     j_nearest = clip(round(X/pitch + (n-1)/2), 0, n-1)
    #     xc        = (j_nearest - (n-1)/2) * pitch
    #
    # Then the local lens coordinate is dX = X - xc, and the lenslet
    # phase is -k/(2f) * (dX^2 + dY^2).  Outside the MLA footprint the
    # phase is left as zero.  This avoids the per-lenslet double loop
    # and brings the cost down from O(N^2 * K^2) to O(N^2) operations.
    half_extent = n_lenslets * pitch / 2
    in_mla = (np.abs(X) < half_extent) & (np.abs(Y) < half_extent)

    jx = np.clip(
        np.round(X / pitch + (n_lenslets - 1) / 2), 0, n_lenslets - 1
    )
    jy = np.clip(
        np.round(Y / pitch + (n_lenslets - 1) / 2), 0, n_lenslets - 1
    )
    xc = (jx - (n_lenslets - 1) / 2) * pitch
    yc = (jy - (n_lenslets - 1) / 2) * pitch

    dX = X - xc
    dY = Y - yc
    r_sq = dX * dX + dY * dY
    phase = np.where(in_mla, -k / (2 * focal_length) * r_sq, 0.0)

    return np.exp(1j * phase)


# ============================================================================
# Dammann grating design (IFTA)
# ============================================================================

def makedammann2d(
    periodx: float = 61.0,
    periody: float = 61.0,
    waveln: float = 1.31,
    wavsamp: float = 0.5,
    phaselevels: int = 8,
    phasesteps: int = 4,
    diforders: np.ndarray = None,
    diffractionthr: float = 0.25,
    nfmov: float = 0.5,
    itr: int = 3000,
    plot: bool = True,
    plot_every: int = 50,
    seed: int = None,
    save_path: str = None,
):
    """
    Design a 2D Dammann grating using an iterative Fourier transform algorithm.

    Uses an IFTA (Iterative Fourier Transform Algorithm) to find a phase-only
    near-field distribution whose Fourier transform produces a uniform array
    of diffraction orders.  Phase quantisation is progressively tightened over
    the iterations (simulated-annealing style).

    Parameters
    ----------
    periodx : float
        Grating period in x (um).
    periody : float
        Grating period in y (um).
    waveln : float
        Design wavelength (um).
    wavsamp : float
        Spatial sampling expressed in wavelengths (e.g. 0.5 -> half-wavelength).
    phaselevels : int
        Number of quantised phase levels in the final grating.
    phasesteps : int
        Annealing schedule exponent -- controls how quickly phase quantisation
        tightens over iterations.
    diforders : np.ndarray or None
        2-D array specifying the target diffraction-order pattern (amplitudes).
        ``None`` defaults to ``np.ones((12, 12))``.
    diffractionthr : float
        Intensity threshold used to identify "active" orders when computing
        uniformity and efficiency metrics.
    nfmov : float
        Near-field blending / momentum factor (0-1).  Smaller values make
        early iterations more conservative.
    itr : int
        Total number of IFTA iterations.
    plot : bool
        If True, display progress plots every *plot_every* iterations and at
        completion.
    plot_every : int
        Plotting cadence (iterations between plot updates).
    seed : int or None
        Random seed for reproducibility.  ``None`` leaves the RNG unseeded.
    save_path : str or None
        If provided, save the final quantized phase (radians) to this file
        in CSV format compatible with :func:`load_phase_file`.

    Returns
    -------
    nearfield : np.ndarray (complex)
        Final near-field distribution (phase-only, quantized to phaselevels).
    farfield : np.ndarray (complex)
        Far-field (Fourier plane) distribution at the last iteration.
    cell_pixel_size : tuple of (float, float)
        Physical pixel spacing (dx, dy) of the near-field array [m].
        For square gratings (periodx == periody), both values are equal.

    Examples
    --------
    >>> # Default 12x12 spot array at 1.31 um
    >>> nf, ff, cell_dx = makedammann2d(plot=False)
    >>>
    >>> # Custom 8x8 array, visible wavelength, fewer phase levels
    >>> nf, ff, cell_dx = makedammann2d(
    ...     periodx=80, periody=80, waveln=0.633,
    ...     diforders=np.ones((8, 8)),
    ...     phaselevels=4, itr=1000, plot=False, seed=42,
    ... )

    Notes
    -----
    Ported to Python by Andrew Traverso from the original Octave/MATLAB
    implementation (makedammann2d.m) by Daniel Marks.
    """
    from numpy.fft import fft2, ifft2, fftshift, ifftshift

    if diforders is None:
        diforders = np.ones((12, 12))
    diforders = np.asarray(diforders, dtype=float)

    if seed is not None:
        np.random.seed(seed)

    # -- Grid sizing -------------------------------------------------------
    ndifordersx = int(np.ceil(periodx / (wavsamp * waveln) * 0.5)) * 2
    ndifordersy = int(np.ceil(periody / (wavsamp * waveln) * 0.5)) * 2

    samplingx = periodx / ndifordersx
    samplingy = periody / ndifordersy

    # -- Target diffraction order pattern ----------------------------------
    # Symmetric centred placement: without this the port from the
    # Octave code's 1-based ``ceil((N - n) / 2) + 1`` fell into an
    # off-by-one when ``(N - n)`` was odd, placing the input pattern
    # one cell to the left of centre.  That broke the binary symmetry
    # Dammann designs depend on.  Plain integer division gives a
    # symmetric embedding in both parities.
    totaldiforders = np.zeros((ndifordersx, ndifordersy))
    x0 = (ndifordersx - diforders.shape[0]) // 2
    y0 = (ndifordersy - diforders.shape[1]) // 2
    totaldiforders[x0:x0 + diforders.shape[0], y0:y0 + diforders.shape[1]] = diforders

    # Axis vectors for plotting
    diforderx_ax = np.arange(-ndifordersx // 2, ndifordersx // 2)
    difordery_ax = np.arange(-ndifordersy // 2, ndifordersy // 2)
    rxscal = (np.arange(-ndifordersx // 2 + 0.5, ndifordersx // 2 - 0.5 + 1e-9)) * samplingx
    ryscal = (np.arange(-ndifordersy // 2 + 0.5, ndifordersy // 2 - 0.5 + 1e-9)) * samplingy

    # -- Initial near-field (separable random phase) -----------------------
    phsx, phsy = np.meshgrid(
        np.random.rand(ndifordersx),
        np.random.rand(ndifordersy),
        indexing='ij',
    )
    nearfield = np.exp(2j * np.pi * (phsx + phsy) - 1j * np.pi)

    # -- Iteration ---------------------------------------------------------
    totaldifnorm = (np.sum(np.abs(totaldiforders) ** 2) / totaldiforders.size) ** 0.5

    farfieldamp = None
    farfield = None

    if plot:
        import matplotlib.pyplot as plt
        plt.ion()
        fig, axes = plt.subplots(1, 3, figsize=(15, 4))

    nfmov_cur = nfmov

    for it in range(itr + 1):
        phaselevelscur = phaselevels * 2 ** int(np.floor(phasesteps * (itr - it) / itr))

        if it == itr:
            nfmov_cur = 0

        # Forward transform (near field -> far field)
        farfield = fftshift(fft2(fftshift(nearfield))) / np.sqrt(nearfield.size)

        # Amplitude replacement in the far field
        if it == 0:
            farfieldamp = totaldiforders.copy()
        else:
            farfieldamp = 0.00001 + (farfieldamp / np.abs(farfield)) * totaldiforders

        # Normalise far-field amplitude
        farfieldamp = farfieldamp * totaldifnorm / np.sqrt(
            np.sum(farfieldamp ** 2) / farfieldamp.size
        )

        # Combine amplitude constraint with current phase
        farfield2 = farfieldamp * np.sign(farfield)

        # Inverse transform (far field -> near field)
        nearfield2 = ifftshift(ifft2(ifftshift(farfield2))) * np.sqrt(farfield2.size)

        # Quantise phase
        phs = (
            np.floor(0.5 + np.angle(nearfield2) * (phaselevelscur / (2 * np.pi)))
            * (2 * np.pi / phaselevelscur)
        )

        # Blending / momentum update
        nfmovitr = nfmov_cur + (1.0 - nfmov_cur) * (it / itr)
        nearfield = (1 - nfmovitr) * nearfield + nfmovitr * (totaldifnorm * np.exp(1j * phs))

        # -- Plotting ------------------------------------------------------
        if plot and (it % plot_every == 0 or it == itr):
            for ax in axes:
                ax.clear()

            axes[0].imshow(
                np.angle(nearfield).T,
                extent=[rxscal[0], rxscal[-1], ryscal[-1], ryscal[0]],
                aspect='auto',
            )
            axes[0].set_title(f'Phase Levels {phaselevelscur}')
            axes[0].set_xlabel('Distance (um)')
            axes[0].set_ylabel('Distance (um)')

            axes[1].imshow(
                np.abs(nearfield).T,
                extent=[rxscal[0], rxscal[-1], ryscal[-1], ryscal[0]],
                aspect='auto',
            )
            axes[1].set_title('Absolute value')
            axes[1].set_xlabel('Distance (um)')
            axes[1].set_ylabel('Distance (um)')

            diffrac = np.abs(farfield) ** 2
            active = diffrac[diffrac > diffractionthr]
            if active.size > 0:
                ratiodif = active.min() / active.max()
                efficiencydif = active.sum() / diffrac.sum()
            else:
                ratiodif = 0.0
                efficiencydif = 0.0

            axes[2].imshow(
                diffrac.T,
                extent=[diforderx_ax[0], diforderx_ax[-1], difordery_ax[-1], difordery_ax[0]],
                aspect='auto',
            )
            axes[2].set_title(
                f'Diffractive power {ratiodif:.4g} ratio, {efficiencydif:.4g} efficiency'
            )
            axes[2].set_xlabel('Diffraction order')
            axes[2].set_ylabel('Diffraction order')

            fig.tight_layout()
            plt.pause(0.25)

    # Final quantization to target phase levels (not binary)
    final_phase = (
        np.floor(0.5 + np.angle(nearfield) * (phaselevels / (2 * np.pi)))
        * (2 * np.pi / phaselevels)
    )
    nearfield = np.exp(1j * final_phase)

    # Physical pixel size
    cell_pixel_size_x = samplingx * 1e-6  # convert um to meters
    cell_pixel_size_y = samplingy * 1e-6
    cell_pixel_size = cell_pixel_size_x  # for square gratings; both returned below

    # Save to file if requested
    if save_path is not None:
        save_phase_file(save_path, final_phase, cell_pixel_size=cell_pixel_size,
                        metadata={
                            'phaselevels': phaselevels,
                            'periodx_um': periodx,
                            'periody_um': periody,
                            'wavelength_um': waveln,
                            'diforders': f'{diforders.shape[0]}x{diforders.shape[1]}',
                        })

    if plot:
        plt.ioff()
        plt.show()

    return nearfield, farfield, (cell_pixel_size_x, cell_pixel_size_y)


# =============================================================================
# FITS FILE I/O (optional — requires astropy)
# =============================================================================

try:
    from astropy.io import fits as _fits
    _ASTROPY_AVAILABLE = True
except ImportError:
    _ASTROPY_AVAILABLE = False


def load_fits_field(filepath, hdu_amplitude=0, hdu_phase=None):
    """
    Load a complex optical field from a FITS file.

    Supports two common formats:
    - Two HDUs: amplitude in one HDU, phase in another
    - Single HDU with complex data or [real, imag] stack along first axis

    Parameters
    ----------
    filepath : str
        Path to the .fits file.
    hdu_amplitude : int, default 0
        HDU index for the amplitude array (or complex array if hdu_phase is None).
    hdu_phase : int or None, default None
        HDU index for the phase array [radians]. If None, ``hdu_amplitude``
        is assumed to contain either complex data or a [real, imag] stack.

    Returns
    -------
    E : ndarray (complex, N×N)
        Complex field.
    metadata : dict
        Selected header keywords (wavelength, dx, dy) if present.

    Notes
    -----
    Requires the ``astropy`` package. Install via ``pip install astropy``.
    """
    if not _ASTROPY_AVAILABLE:
        raise ImportError("astropy is required for FITS support. "
                          "Install with: pip install astropy")

    with _fits.open(filepath) as hdul:
        amp_data = np.array(hdul[hdu_amplitude].data)
        header = dict(hdul[hdu_amplitude].header)

        if hdu_phase is not None:
            phase_data = np.array(hdul[hdu_phase].data)
            E = amp_data * np.exp(1j * phase_data)
        elif amp_data.ndim == 3 and amp_data.shape[0] == 2:
            E = amp_data[0] + 1j * amp_data[1]
        elif np.iscomplexobj(amp_data):
            E = amp_data.astype(complex)
        else:
            # Amplitude only — assume zero phase
            E = amp_data.astype(complex)

    metadata = {
        'wavelength': header.get('WAVELENG'),
        'dx': header.get('DX') or header.get('PIXSCALE'),
        'dy': header.get('DY') or header.get('PIXSCALE'),
    }
    return E, metadata


def save_fits_field(filepath, E, wavelength=None, dx=None, dy=None,
                     metadata=None, split_amp_phase=True):
    """
    Save a complex optical field to a FITS file.

    Parameters
    ----------
    filepath : str
        Output .fits path.
    E : ndarray (complex, N×N)
        Complex field to save.
    wavelength : float, optional
        Wavelength [m]. Stored as WAVELENG header keyword.
    dx, dy : float, optional
        Grid spacings [m]. Stored as DX, DY header keywords.
    metadata : dict, optional
        Additional header keywords to include.
    split_amp_phase : bool, default True
        If True, save as two HDUs (amplitude + phase).
        If False, save as a single 3D array [real, imag, ...].

    Notes
    -----
    Requires ``astropy``. The split format (default) is more widely
    compatible with standard astronomy tools.
    """
    if not _ASTROPY_AVAILABLE:
        raise ImportError("astropy is required for FITS support. "
                          "Install with: pip install astropy")

    header = _fits.Header()
    if wavelength is not None:
        header['WAVELENG'] = (wavelength, 'Wavelength [m]')
    if dx is not None:
        header['DX'] = (dx, 'Grid spacing in x [m]')
    if dy is not None:
        header['DY'] = (dy, 'Grid spacing in y [m]')
    if metadata:
        for key, value in metadata.items():
            header[key.upper()[:8]] = value

    if split_amp_phase:
        amp = np.abs(E).astype(np.float32)
        phase = np.angle(E).astype(np.float32)

        primary = _fits.PrimaryHDU(amp, header=header)
        primary.header['EXTNAME'] = 'AMPLITUDE'

        phase_hdu = _fits.ImageHDU(phase)
        phase_hdu.header['EXTNAME'] = 'PHASE'
        phase_hdu.header['BUNIT'] = 'radians'

        _fits.HDUList([primary, phase_hdu]).writeto(filepath, overwrite=True)
    else:
        stacked = np.stack([np.real(E), np.imag(E)]).astype(np.float32)
        primary = _fits.PrimaryHDU(stacked, header=header)
        primary.header['FORMAT'] = 'real_imag_stack'
        primary.writeto(filepath, overwrite=True)
