"""
CODE V ``.seq`` sequential-file prescription I/O.

Reader / writer for the CODE V sequential file format.  Covers the
common subset: spherical + conic surfaces, one wavelength, circular
aperture, on-axis field.  Round-trips cleanly between
:func:`export_codev_seq` and :func:`load_codev_seq`.

v5.1.0 split (Agent F): extracted from ``lumenairy/io/prescriptions.py``
without any logic change.  Public API is unchanged: every name in this
module is re-exported through ``lumenairy.io.prescriptions`` and
``lumenairy``.

Author: Andrew Traverso
"""

from __future__ import annotations

import os
import warnings
from typing import Any, Dict, Optional

import numpy as np

# ============================================================================
# CODE V .seq (sequence) file I/O
# ============================================================================


def export_codev_seq(prescription: Dict[str, Any], path: str, *,
                     wavelength: float,
                     stop_surface: Optional[int] = None,
                     aperture_diameter: Optional[float] = None,
                     back_focal_length: Optional[float] = None,
                     name: Optional[str] = None,
                     units: str = 'M') -> None:
    """Write a CODE V sequential ``.seq`` file for a prescription.

    The produced file uses the canonical CODE V ``LEN NEW`` / ``DIM`` /
    ``WL`` header followed by one surface block per refracting surface
    (``RDY`` / ``THI`` / ``GLA`` / optional ``CON`` / ``STO``) and an
    image plane at the end.

    Parameters
    ----------
    prescription : dict
        Same format used by :func:`apply_real_lens` and
        :func:`export_zemax_zmx`: ``{'surfaces': [...],
        'thicknesses': [...], 'aperture_diameter': ...}``.
    path : str
        Output ``.seq`` file path.
    wavelength : float
        Wavelength [m] to write in the header.
    stop_surface : int
        Zero-based index of the stop among refracting surfaces.
    aperture_diameter : float, optional
        Entrance-pupil diameter in meters; falls back to
        ``prescription['aperture_diameter']``.
    back_focal_length : float, optional
        BFL [m] from last refracting surface to image plane; defaults to 0.
    name : str, optional
        Lens name written as a ``! title`` comment.
    units : {'M', 'MM', 'IN'}, default 'M'
        Physical-length unit written on the ``DIM`` line.  Library
        prescriptions are SI meters; 'MM'/'IN' trigger conversion on
        write (useful for handing files to CODE V users).

    Notes
    -----
    CODE V's full ``.seq`` syntax covers several hundred commands
    (freeforms, multi-configurations, diffractive surfaces,
    zoom positions, tolerances, user-defined surfaces, ...).  This
    writer emits the common subset: spherical + conic surfaces,
    one wavelength, circular aperture, on-axis field.  Round-trips
    cleanly with :func:`load_codev_seq`; more exotic surface types
    must be hand-edited.
    """
    surfaces = prescription['surfaces']
    thicknesses = prescription['thicknesses']
    # v5.4.6 (audit F-29): default stop_surface to the prescription's own
    # stop (stop_index, else per-surface is_stop), not surface 0, so a
    # load->export->load round trip preserves the aperture stop.
    if stop_surface is None:
        stop_surface = prescription.get('stop_index')
        if stop_surface is None:
            stop_surface = next(
                (i for i, s in enumerate(surfaces) if s.get('is_stop')), 0)
    stop_surface = int(stop_surface)
    if aperture_diameter is None:
        aperture_diameter = prescription.get('aperture_diameter', 25.4e-3)
    bfl = back_focal_length or 0.0

    name = name or prescription.get('name',
        os.path.splitext(os.path.basename(path))[0])

    units = str(units).upper()
    if units not in ('M', 'MM', 'IN'):
        raise ValueError(
            f"export_codev_seq: units must be M, MM, or IN (got {units!r})")
    scale = {'M': 1.0, 'MM': 1e3, 'IN': 1.0 / 0.0254}[units]

    def _fmt(v):
        if v is None or np.isinf(v):
            return 'INFINITY'
        return f'{v * scale:.8f}'

    wvl_nm = wavelength * 1e9

    lines = []
    lines.append('! Generated by lumenairy (export_codev_seq)')
    lines.append(f'! {name}')
    lines.append('LEN NEW')
    lines.append(f'DIM {units}')
    lines.append(f'WL {wvl_nm:.4f}')
    lines.append('REF 1')
    lines.append(
        f'APE F1 CIR R {aperture_diameter * 0.5 * scale:.6f}')

    # CODE V .seq surface blocks.  We write object (S0), refracting
    # surfaces (S1..Sn), and image plane.  Thicknesses in library
    # prescriptions are gap-after-surface; the same convention holds for
    # CODE V's THI.
    lines.append('!')
    lines.append('! Object surface')
    lines.append('SO')
    lines.append('  RDY INFINITY')
    lines.append('  THI INFINITY')
    lines.append('')

    for i, surf in enumerate(surfaces):
        R = surf.get('radius')
        conic = surf.get('conic', 0.0) or 0.0
        glass = surf.get('glass_after', '')
        t_m = thicknesses[i] if i < len(thicknesses) else bfl

        lines.append(f'! Surface {i + 1}')
        lines.append(f'S{i + 1}')
        if i == stop_surface:
            lines.append('  STO')
        lines.append(f'  RDY {_fmt(R)}')
        lines.append(f'  THI {_fmt(t_m)}')
        if glass and glass.lower() not in ('air', ''):
            lines.append(f'  GLA {glass}')
        if conic != 0.0:
            lines.append(f'  CON {conic:.8f}')
        lines.append('')

    # Image surface
    lines.append('! Image surface')
    lines.append('SI')
    lines.append('  RDY INFINITY')
    lines.append(f'  THI {_fmt(bfl)}')
    lines.append('')

    lines.append('GO')
    lines.append('END')

    with open(path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')


def load_codev_seq(filepath: str,
                   name: Optional[str] = None) -> Dict[str, Any]:
    """Parse a CODE V ``.seq`` file into a library prescription dict.

    Reads the common subset emitted by :func:`export_codev_seq` plus
    several conventional variants:

    * ``DIM M`` / ``DIM MM`` / ``DIM IN`` — unit handling
    * ``WL <nm>`` — wavelength (not round-tripped, but stored in the
      returned dict under key ``wavelength``)
    * ``S<i>`` headers or ``SO`` / ``SI`` markers
    * ``RDY <val>`` / ``CUY <c>`` — radius or curvature (``CUY`` is
      converted via ``R = 1/c``)
    * ``THI <val>`` — thickness
    * ``GLA <name>`` — glass (``GLA AIR`` or ``GLA`` omitted = air)
    * ``CON <k>`` — conic constant
    * ``STO`` — aperture stop surface
    * ``APE F1 CIR R <r>`` — aperture radius

    Returns a dict of the same shape as :func:`make_singlet`:
    ``{'name', 'aperture_diameter', 'surfaces', 'thicknesses',
       'wavelength', 'stop_index'}``.

    Unknown commands are silently ignored so that files written by
    CODE V with extra boilerplate (tolerancing directives, zoom
    positions, spot-diagram commands, ...) still parse.
    """
    with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
        raw = f.read()

    # Strip comments (lines starting with '!') and blank lines.
    lines_iter = []
    for ln in raw.splitlines():
        s = ln.strip()
        if not s or s.startswith('!'):
            continue
        lines_iter.append(s)

    units = 'M'
    wavelength_m = None
    aperture_diameter_m = None

    # Surface blocks as we encounter them.  `current` is a dict mutated
    # while inside S<i> / SO / SI; flushed to `surfaces` on the next
    # surface header or END.
    surfaces_raw = []
    current = None
    # v4.13.2 (C-P0-4): also capture the optional SI image-plane block
    # so callers can recover the BFL from a `.seq` file that uses the
    # standard CODE V convention of encoding the back-focal length on
    # the image-plane THI.
    image_plane_thi = None
    # CV-1 (AUDIT_IO_PRESCRIPTIONS): track dropped shape/fold directives so a
    # folded / aspheric ``.seq`` doesn't import as a silently straight-axis /
    # base-conic system.  CODE V encodes folds as XDE/YDE/ZDE (decenters) and
    # ADE/BDE/CDE (tilts), and aspheres via ASP/SDG -- none are parsed here,
    # so we warn once (rather than silently) that they were ignored.
    _dropped_geometry_cmds: set = set()
    _CV_FOLD_CMDS = frozenset({'XDE', 'YDE', 'ZDE', 'ADE', 'BDE', 'CDE'})
    _CV_ASPHERE_CMDS = frozenset({'ASP', 'SDG'})

    def _unit_to_meters(v):
        if v is None:
            return None
        return {'M': 1.0, 'MM': 1e-3,
                'IN': 0.0254}[units] * float(v)

    def _flush():
        nonlocal current, image_plane_thi
        if current is not None:
            if current.get('kind') == 'refracting':
                surfaces_raw.append(current)
            elif current.get('kind') == 'image':
                # Preserve the image-plane THI for BFL recovery.
                if current.get('thickness') is not None:
                    image_plane_thi = current.get('thickness')
        current = None

    i = 0
    while i < len(lines_iter):
        tokens = lines_iter[i].split()
        cmd = tokens[0].upper()

        if cmd == 'LEN' or cmd == 'GO' or cmd == 'END' or cmd == 'REF':
            if cmd == 'END':
                _flush()
                break
            i += 1
            continue

        if cmd == 'DIM':
            if len(tokens) >= 2:
                unit_tok = tokens[1].upper()
                if unit_tok in ('M', 'MM', 'IN'):
                    units = unit_tok
            i += 1
            continue

        if cmd == 'WL':
            if len(tokens) >= 2:
                try:
                    wavelength_m = float(tokens[1]) * 1e-9
                except ValueError:
                    pass
            i += 1
            continue

        if cmd == 'APE':
            # APE F1 CIR R <radius>  or  APE CIR R <radius>
            for j, tk in enumerate(tokens):
                if tk.upper() == 'R' and j + 1 < len(tokens):
                    try:
                        r = float(tokens[j + 1])
                        aperture_diameter_m = 2.0 * _unit_to_meters(r)
                    except ValueError:
                        pass
                    break
            i += 1
            continue

        # Surface headers.  Accept S<int>, SO, SI, SIM.
        if cmd == 'SO':
            _flush()
            current = {'kind': 'object'}
            i += 1
            continue
        if cmd in ('SI', 'SIM'):
            _flush()
            current = {'kind': 'image'}
            i += 1
            continue
        if cmd.startswith('S') and len(cmd) > 1 and cmd[1:].isdigit():
            _flush()
            current = {'kind': 'refracting',
                       'index': int(cmd[1:]),
                       'radius': None, 'conic': 0.0,
                       'thickness': 0.0, 'glass': 'air',
                       'is_stop': False}
            i += 1
            continue

        # Commands that apply to the current surface block
        if current is None:
            i += 1
            continue

        if cmd == 'STO':
            if current.get('kind') == 'refracting':
                current['is_stop'] = True
                # CV-nit (AUDIT_IO_PRESCRIPTIONS): dropped the dead
                # ``current['index']`` read-and-discard (refactor residue).
            i += 1
            continue

        if cmd == 'RDY':
            if len(tokens) >= 2:
                val = tokens[1]
                if val.upper() == 'INFINITY' or val.upper() == 'INF':
                    current['radius'] = float('inf')
                else:
                    try:
                        current['radius'] = _unit_to_meters(float(val))
                    except ValueError:
                        pass
            i += 1
            continue

        if cmd == 'CUY':
            if len(tokens) >= 2:
                try:
                    c = float(tokens[1])
                    current['radius'] = (float('inf') if c == 0
                                         else 1.0 / c / {
                        'M': 1.0, 'MM': 1e3,
                        'IN': 1.0 / 0.0254}[units])
                except ValueError:
                    pass
            i += 1
            continue

        if cmd == 'THI':
            if len(tokens) >= 2:
                val = tokens[1]
                if val.upper() == 'INFINITY' or val.upper() == 'INF':
                    current['thickness'] = float('inf')
                else:
                    try:
                        current['thickness'] = _unit_to_meters(float(val))
                    except ValueError:
                        pass
            i += 1
            continue

        if cmd == 'GLA':
            if len(tokens) >= 2:
                g = tokens[1]
                current['glass'] = (
                    'air' if g.upper() in ('AIR', '') else g)
            i += 1
            continue

        if cmd == 'CON':
            if len(tokens) >= 2:
                try:
                    current['conic'] = float(tokens[1])
                except ValueError:
                    pass
            i += 1
            continue

        # CV-1: record dropped fold / aspheric directives so they can be
        # surfaced once (below) rather than silently swallowed by the
        # unknown-directive fallthrough -- a folded / aspheric .seq otherwise
        # imports as a straight-axis / base-conic system with no signal.
        if cmd in _CV_FOLD_CMDS or cmd in _CV_ASPHERE_CMDS:
            _dropped_geometry_cmds.add(cmd)
        # Unknown directive — ignore
        i += 1

    if _dropped_geometry_cmds:
        _fold = sorted(_dropped_geometry_cmds & _CV_FOLD_CMDS)
        _asph = sorted(_dropped_geometry_cmds & _CV_ASPHERE_CMDS)
        _parts = []
        if _fold:
            _parts.append(
                f"coordinate decenter/tilt (fold) directives {_fold} -- the "
                f"design imports as STRAIGHT-AXIS with the fold geometry gone")
        if _asph:
            _parts.append(
                f"aspheric directives {_asph} -- aspheric surfaces degrade to "
                f"base conic")
        warnings.warn(
            f"load_codev_seq({os.path.basename(filepath)!r}): dropped "
            f"unparsed shape/geometry directives -- "
            f"{'; '.join(_parts)}.  This loader does not yet parse them; the "
            f"loaded prescription is missing that geometry.",
            UserWarning, stacklevel=2)

    _flush()

    if not surfaces_raw:
        raise ValueError(
            f"load_codev_seq: no refracting surfaces found in "
            f"{filepath!r}.  Check the file is a valid CODE V .seq.")

    # Build the library prescription
    surfaces = []
    thicknesses = []
    prev_glass = 'air'
    # The last refracting surface's thickness goes to the image plane,
    # not the prescription's `thicknesses` list (library convention is
    # that `thicknesses[i]` is the gap AFTER surface i, stopping at the
    # last refracting surface; the final image-plane gap is the BFL and
    # not part of the prescription).  v4.13.2 (C-P0-4): capture the
    # last surface's THI as ``back_focal_length`` (image distance) so
    # externally-authored `.seq` files where the BFL is encoded as the
    # last surface's THI -- a legitimate CODE V convention -- no longer
    # silently drop the BFL on read.  Round-trips through
    # :func:`export_codev_seq` are now lossless.
    last_surface_thickness = 0.0
    for i, s in enumerate(surfaces_raw):
        surf_dict = {
            'radius': s.get('radius', float('inf')),
            'conic': s.get('conic', 0.0),
            'aspheric_coeffs': None,
            'radius_y': None, 'conic_y': None,
            'aspheric_coeffs_y': None,
            'glass_before': prev_glass,
            'glass_after': s.get('glass', 'air'),
        }
        surfaces.append(surf_dict)
        if i < len(surfaces_raw) - 1:
            thicknesses.append(s.get('thickness', 0.0))
        else:
            last_surface_thickness = s.get('thickness', 0.0)
        prev_glass = s.get('glass', 'air')

    # Figure out the stop index (0-based among refracting surfaces).
    stop_index = None
    for i, s in enumerate(surfaces_raw):
        if s.get('is_stop'):
            stop_index = i
            break

    result = {
        'name': name or os.path.splitext(os.path.basename(filepath))[0],
        'aperture_diameter': aperture_diameter_m or 25.4e-3,
        'surfaces': surfaces,
        'thicknesses': thicknesses,
    }
    if wavelength_m is not None:
        result['wavelength'] = wavelength_m
    if stop_index is not None:
        result['stop_index'] = stop_index
    # v4.13.2 (C-P0-4): preserve the BFL.  Prefer the SI image-plane
    # THI if present (matches what :func:`export_codev_seq` writes);
    # otherwise fall back to the last refracting surface's THI, which
    # is the convention used by some external CODE V authors.
    bfl = image_plane_thi
    if bfl is None or bfl == 0.0:
        bfl = last_surface_thickness
    if bfl is not None and bfl != 0.0 and np.isfinite(bfl):
        result['back_focal_length'] = float(bfl)
    return result


# A-13ish (AUDIT_ADVERSARIAL_CODEBASE 2026-07-25): declare the public
# surface explicitly, matching the convention every ``analysis/`` module
# already follows.  Every name here is re-exported through
#  ``lumenairy.io.prescriptions`` (v5.1.0 split) and the top-level facade.
__all__ = [
    'load_codev_seq',
    'export_codev_seq',
]
