"""
CODE V ``.seq`` sequential-file prescription I/O.

Reader / writer for the CODE V sequential file format.  Covers the
common subset: spherical + conic surfaces, one wavelength, circular
aperture, on-axis field.  Round-trips cleanly between
:func:`export_codev_seq` and :func:`load_codev_seq`.

v5.1.0 split (Agent F): extracted from ``lumenairy/io/prescriptions.py``
without any logic change.  Public API is unchanged: every name in this
module is re-exported through ``lumenairy.io.prescriptions`` and
``lumenairy``.

Author: Andrew Traverso
"""

from __future__ import annotations

import os
import re
import warnings
from typing import Any, Dict, Optional

import numpy as np

from ..glass import GLASS_REGISTRY
from .prescriptions_zemax import _warn_dropped_anamorphic

# ============================================================================
# CODE V .seq (sequence) file I/O
# ============================================================================

# CODE V's ``DIM`` command takes exactly three lens-unit tokens:
#   ``M`` = MILLIMETRES, ``C`` = centimetres, ``I`` = inches.
# The language has no metre unit -- ``DIM M`` is *millimetres*, not metres.
# ``MM`` / ``CM`` / ``IN`` / ``INCH`` are tolerated aliases on READ only (they
# are not CODE V tokens; some third-party writers emit them, and every file
# this library wrote before v5.46 used ``MM`` for millimetres).
_CV_DIM_TO_METERS = {
    'M': 1e-3, 'C': 1e-2, 'I': 0.0254,
    # tolerated read-side aliases
    'MM': 1e-3, 'CM': 1e-2, 'IN': 0.0254, 'INCH': 0.0254, 'INCHES': 0.0254,
}
# Canonical CODE V token to EMIT for each accepted ``units=`` spelling, so a
# file this library writes is always readable by CODE V itself.
_CV_UNITS_CANONICAL = {
    'M': 'M', 'MM': 'M',
    'C': 'C', 'CM': 'C',
    'I': 'I', 'IN': 'I', 'INCH': 'I', 'INCHES': 'I',
}

# I1 (AUDIT_ADVERSARIAL_EXHAUSTIVE 2026-09-11) migration marker.  Files written
# by this library BEFORE v5.46 carry ``! Generated by lumenairy
# (export_codev_seq)`` and a ``DIM M`` line whose numbers are SI METRES -- the
# pre-fix writer's private dialect.  The writer now stamps the format line
# below, so a reader can tell the two apart exactly: banner + no marker =
# legacy metres; marker present (or no lumenairy banner at all) = CODE V
# lens units.  See ``load_codev_seq``'s *Migration* note.
_CV_WRITER_BANNER = '! Generated by lumenairy (export_codev_seq)'
_CV_FORMAT_MARKER = '! LUMENAIRY-SEQ-FORMAT 2'
# Prefix used to RECOGNISE the marker on read: any ``LUMENAIRY-SEQ-FORMAT n``
# with n >= 2 is a file written in CODE V lens units, so a future format bump
# must not make every v5.46 file look legacy again.
_CV_FORMAT_MARKER_PREFIX = '! LUMENAIRY-SEQ-FORMAT'
_CV_FORMAT_NOTE = ('! DIM lens units follow CODE V: M = millimetres, '
                   'C = centimetres, I = inches.')

# CODE V's rotationally-symmetric asphere:
#   z = c y^2 / (1 + sqrt(1 - (1+K) c^2 y^2)) + A y^4 + B y^6 + C y^8 + ...
# The letter sequence skips ``I`` (it reads as a 1), so letter index n (1-based)
# carries the radial power 2n + 2.
# The PRE-v5.46 writer's own unit table.  It accepted ``units='M'`` (which it
# wrote as SI metres under a ``DIM M`` line -- the I1 defect), but also
# ``'MM'`` and ``'IN'``, which it scaled correctly and labelled with the token
# it means.  A legacy file must therefore be read with THIS table, not with a
# blanket metre scale: a pre-v5.46 ``DIM MM`` file carries millimetres and a
# ``DIM IN`` file inches, and only ``DIM M`` is the ambiguous case.
_CV_LEGACY_TO_METERS = {'M': 1.0, 'MM': 1e-3, 'IN': 0.0254}

_CV_ASPH_LETTERS = ('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'J')
_CV_ASPH_LETTER_TO_POWER = {
    ch: 2 * (n + 1) + 2 for n, ch in enumerate(_CV_ASPH_LETTERS)
}
_CV_ASPH_POWER_TO_LETTER = {
    p: ch for ch, p in _CV_ASPH_LETTER_TO_POWER.items()
}

# I5/I8: a glass name or a title that reaches a writer must not be able to
# invent records (a newline), open a comment (``!``) or break the
# whitespace-split tokenizer on the way back in.
_CV_SAFE_TOKEN_RE = re.compile(r'[A-Za-z0-9_\-\.\+:]+')


def _sanitize_seq_text(text: Any) -> str:
    """Collapse any record-injecting whitespace / comment char in free text."""
    s = '' if text is None else str(text)
    return re.sub(r'\s+', ' ', s.replace('!', ' ')).strip()


def _sanitize_seq_token(tok: Any) -> str:
    """Return ``tok`` reduced to the characters a CODE V name may carry.

    A ``GLA`` value is read back by whitespace-split, so any whitespace in it
    would silently truncate the name; anything outside the safe set is dropped
    rather than written, so an exported file can never carry a token that
    re-reads as something else.
    """
    s = '' if tok is None else str(tok)
    kept = ''.join(_CV_SAFE_TOKEN_RE.findall(s))
    if kept != s:
        warnings.warn(
            f"export_codev_seq: name token {s!r} carries characters CODE V's "
            f"tokenizer cannot round-trip; writing {kept!r} instead.  Rename "
            f"the glass / surface so the exported file means what you think.",
            UserWarning, stacklevel=3)
    return kept


def export_codev_seq(prescription: Dict[str, Any], path: str, *,
                     wavelength: float,
                     stop_surface: Optional[int] = None,
                     aperture_diameter: Optional[float] = None,
                     back_focal_length: Optional[float] = None,
                     name: Optional[str] = None,
                     units: str = 'M') -> None:
    """Write a CODE V sequential ``.seq`` file for a prescription.

    The produced file uses the canonical CODE V ``LEN NEW`` / ``DIM`` /
    ``WL`` header followed by one surface block per surface
    (``RDY`` / ``THI`` / ``GLA`` / optional ``K`` conic / ``ASP`` +
    ``A``..``J`` aspheric coefficients / ``REFL`` mirror flag / ``STO``)
    and an image plane at the end.

    When the prescription carries the full ``elements`` list and any of
    them is a mirror (``element_type='mirror'``), the writer walks that
    list and emits ``REFL`` for each mirror, so a folded design written
    here reloads as a folded design (I3).  Otherwise the pre-existing
    refractive-only ``surfaces`` / ``thicknesses`` path is used.

    Parameters
    ----------
    prescription : dict
        Same format used by :func:`apply_real_lens` and
        :func:`export_zemax_zmx`: ``{'surfaces': [...],
        'thicknesses': [...], 'aperture_diameter': ...}``.
    path : str
        Output ``.seq`` file path.
    wavelength : float
        Wavelength [m] to write in the header.
    stop_surface : int
        Zero-based index of the stop among refracting surfaces.
    aperture_diameter : float, optional
        Entrance-pupil diameter in meters; falls back to
        ``prescription['aperture_diameter']``.
    back_focal_length : float, optional
        BFL [m] from last refracting surface to image plane; defaults to 0.
    name : str, optional
        Lens name written as a ``! title`` comment.
    units : {'M', 'C', 'I'}, default 'M'
        CODE V **lens unit** written on the ``DIM`` line: ``'M'``
        millimetres (CODE V's default), ``'C'`` centimetres, ``'I'``
        inches.  The aliases ``'MM'`` / ``'CM'`` / ``'IN'`` / ``'INCH'``
        are accepted and normalised to the CODE V token they mean.
        Library prescriptions are SI metres; the values written are
        converted to the chosen lens unit.

    Notes
    -----
    CODE V's full ``.seq`` syntax covers several hundred commands
    (freeforms, multi-configurations, diffractive surfaces,
    zoom positions, tolerances, user-defined surfaces, ...).  This
    writer emits the common subset: spherical + conic surfaces,
    one wavelength, circular aperture, on-axis field.  Round-trips
    cleanly with :func:`load_codev_seq`; more exotic surface types
    must be hand-edited.

    Anamorphic keys (``radius_y`` / ``conic_y`` / ``aspheric_coeffs_y``)
    have no CODE V emission path here: a ``YTO`` toroid / biconic block
    is not written, so a cylindrical or biconic surface would export as a
    rotationally-symmetric sphere.  Rather than do that silently the
    writer raises the same loud :class:`UserWarning` the Zemax writer
    raises for a dropped Forbes-Q surface (I4).

    **Units migration (v5.46).**  ``units='M'`` now means CODE V's own
    ``DIM M`` = *millimetres*, so the emitted numbers are 1000x the
    pre-v5.46 output and the file is finally correct when CODE V opens
    it.  Files written before v5.46 carry ``DIM M`` with SI-metre
    numbers; :func:`load_codev_seq` detects them from this writer's
    banner and reads them with the legacy scale (warning as it does).
    """
    surfaces = prescription['surfaces']
    thicknesses = prescription['thicknesses']
    # I3: prefer the full chronological element list when it carries a mirror,
    # so a folded design survives the round trip (the refractive-only
    # ``surfaces`` list has no mirror entries at all).  Same dispatch shape as
    # ``export_zemax_zmx`` -> ``_export_zemax_zmx_full``.
    _elements = prescription.get('elements')
    _all_th = prescription.get('all_thicknesses')
    if (_elements is not None
            and any(isinstance(e, dict)
                    and (e.get('element_type') == 'mirror' or e.get('is_mirror'))
                    for e in _elements)):
        walk = list(_elements)
        walk_th = list(_all_th if _all_th is not None else thicknesses)
    else:
        walk = list(surfaces)
        walk_th = list(thicknesses)
    # Default stop_surface to the prescription's own
    # stop (stop_index, else per-surface is_stop), not surface 0, so a
    # load->export->load round trip preserves the aperture stop.
    if stop_surface is None:
        stop_surface = prescription.get('stop_index')
        if stop_surface is None:
            stop_surface = next(
                (i for i, s in enumerate(surfaces) if s.get('is_stop')), 0)
    stop_surface = int(stop_surface)
    if aperture_diameter is None:
        aperture_diameter = prescription.get('aperture_diameter', 25.4e-3)
    bfl = back_focal_length or 0.0

    name = name or prescription.get('name',
        os.path.splitext(os.path.basename(path))[0])

    units = str(units).upper()
    if units not in _CV_UNITS_CANONICAL:
        raise ValueError(
            f"export_codev_seq: units must be one of the CODE V DIM tokens "
            f"M (millimetres), C (centimetres), I (inches) -- or an alias "
            f"{sorted(set(_CV_UNITS_CANONICAL) - {'M', 'C', 'I'})} -- "
            f"got {units!r}")
    # I1: emit the CODE V token, not the alias the caller happened to spell
    # (CODE V's DIM command does not accept 'MM' / 'CM' / 'IN').
    units = _CV_UNITS_CANONICAL[units]
    # metres -> lens units.  I1: pre-v5.46 this was {'M': 1.0, ...}, i.e. the
    # writer labelled SI metres as CODE V's millimetre token, so every file
    # handed to CODE V was 1000x too large.
    scale = 1.0 / _CV_DIM_TO_METERS[units]

    def _fmt(v):
        if v is None or np.isinf(v):
            return 'INFINITY'
        return f'{v * scale:.8f}'

    wvl_nm = wavelength * 1e9

    # I4: a one-axis (cylindrical / biconic / anamorphic-aspheric) surface has
    # no representation in the subset this writer emits.  Warn per surface, as
    # loudly as the Zemax writer's ``_warn_dropped_qtype``, instead of writing
    # a rotationally-symmetric sphere with no diagnostic.
    _warn_dropped_anamorphic(walk, 'export_codev_seq', path)

    # I8: a newline (or a stray '!' ) inside ``name`` would inject arbitrary
    # records into the emitted file; the title is a comment, so collapse it.
    name = _sanitize_seq_text(name)

    lines = []
    lines.append(_CV_WRITER_BANNER)
    lines.append(_CV_FORMAT_MARKER)
    lines.append(_CV_FORMAT_NOTE)
    lines.append(f'! {name}')
    lines.append('LEN NEW')
    lines.append(f'DIM {units}')
    lines.append(f'WL {wvl_nm:.4f}')
    lines.append('REF 1')
    lines.append(
        f'APE F1 CIR R {aperture_diameter * 0.5 * scale:.6f}')

    # CODE V .seq surface blocks.  We write object (S0), refracting
    # surfaces (S1..Sn), and image plane.  Thicknesses in library
    # prescriptions are gap-after-surface; the same convention holds for
    # CODE V's THI.
    lines.append('!')
    lines.append('! Object surface')
    lines.append('SO')
    lines.append('  RDY INFINITY')
    lines.append('  THI INFINITY')
    lines.append('')

    refr_counter = -1
    for i, surf in enumerate(walk):
        is_mirror = (surf.get('element_type') == 'mirror'
                     or bool(surf.get('is_mirror')))
        R = surf.get('radius')
        conic = surf.get('conic', 0.0) or 0.0
        glass = surf.get('glass_after', '')
        t_m = walk_th[i] if i < len(walk_th) else bfl

        lines.append(f'! Surface {i + 1}')
        lines.append(f'S{i + 1}')
        # ``stop_surface`` indexes the REFRACTIVE subset (the F-29 contract
        # every writer here shares), so count refractives, not raw slots.
        if not is_mirror:
            refr_counter += 1
        if (not is_mirror) and refr_counter == stop_surface:
            lines.append('  STO')
        lines.append(f'  RDY {_fmt(R)}')
        lines.append(f'  THI {_fmt(t_m)}')
        if (not is_mirror) and glass and glass.lower() not in ('air', ''):
            lines.append(f'  GLA {_sanitize_seq_token(glass)}')
        # I3: ``K`` is CODE V's own conic keyword.  Pre-v5.46 the writer
        # emitted ``CON`` -- the token its own reader happened to accept --
        # which CODE V does not define; the reader still accepts both.
        if conic != 0.0:
            lines.append(f'  K {conic:.8f}')
        # I3: even-aspheric coefficients as CODE V's ASP block.  CODE V's
        # polynomial is A*y^4 + B*y^6 + C*y^8 + D*y^10 + ... (the letter I is
        # skipped), i.e. letter index n -> radial power 2n + 2.  The library
        # stores a_p in m^(1-p); a lens-unit file wants a_file = a_p *
        # L^(p-1) with L the lens unit in metres -- the exact inverse of the
        # reader's ``a_p = a_file / L**(p-1)`` (same rule the Zemax writer
        # applies with L = 1e-3).
        asph = surf.get('aspheric_coeffs') or {}
        _asp_lines = []
        _asp_dropped = {}
        for power in sorted(asph):
            letter = _CV_ASPH_POWER_TO_LETTER.get(int(power))
            if letter is None:
                _asp_dropped[int(power)] = asph[power]
                continue
            a_file = float(asph[power]) * (_CV_DIM_TO_METERS[units]
                                           ** (int(power) - 1))
            _asp_lines.append(f'  {letter} {a_file:.10E}')
        if _asp_dropped:
            warnings.warn(
                f"export_codev_seq({os.path.basename(path)!r}): surface {i} "
                f"carries aspheric term(s) {_asp_dropped} whose radial power "
                f"is outside CODE V's A..J block (even powers 4..20); they "
                f"are NOT written and the exported surface is shallower than "
                f"the design.",
                UserWarning, stacklevel=2)
        if _asp_lines:
            lines.append('  ASP')
            lines.extend(_asp_lines)
        # I3: CODE V's reflective-surface flag.  Emitted last so the surface
        # block reads the way CODE V's own writer orders it.
        if is_mirror:
            lines.append('  REFL')
        lines.append('')

    # Image surface
    lines.append('! Image surface')
    lines.append('SI')
    lines.append('  RDY INFINITY')
    lines.append(f'  THI {_fmt(bfl)}')
    lines.append('')

    lines.append('GO')
    lines.append('END')

    with open(path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')


def load_codev_seq(filepath: str,
                   name: Optional[str] = None,
                   *,
                   dim_units: Optional[str] = None) -> Dict[str, Any]:
    """Parse a CODE V ``.seq`` file into a library prescription dict.

    Reads the common subset emitted by :func:`export_codev_seq` plus
    several conventional variants:

    * ``DIM M`` / ``DIM C`` / ``DIM I`` — CODE V lens units
      (**millimetres** / centimetres / inches).  ``MM`` / ``CM`` / ``IN``
      / ``INCH`` are tolerated aliases; any other token warns and leaves
      the current unit in force.
    * ``WL <nm>`` — wavelength (not round-tripped, but stored in the
      returned dict under key ``wavelength``)
    * ``S<i>`` headers or ``SO`` / ``SI`` markers
    * ``RDY <val>`` / ``CUY <c>`` — radius or curvature (``CUY`` is
      converted via ``R = 1/c``).  A surface with neither reads as a
      flat (``inf``) dummy surface.
    * ``THI <val>`` — thickness
    * ``GLA <name>`` — glass (``GLA AIR`` or ``GLA`` omitted = air);
      names missing from ``GLASS_REGISTRY`` warn, as in the Zemax loaders
    * ``K <k>`` — conic constant (``CON`` is accepted as the alias this
      library's own writer emitted before v5.46)
    * ``A``..``J`` — even-aspheric coefficients on ``y^4``..``y^20``,
      converted to the library's ``aspheric_coeffs`` convention
    * ``REFL`` / ``RMD REFL`` — reflective surface (imports as an
      ``element_type='mirror'`` entry in ``elements``)
    * ``STO`` — aperture stop surface
    * ``APE F1 CIR R <r>`` — aperture radius

    Parameters
    ----------
    filepath : str
        Path to the ``.seq`` file.
    name : str, optional
        Name for the returned prescription; defaults to the file stem.
    dim_units : {'M', 'C', 'I', 'MM', 'CM', 'IN', 'SI'}, optional
        Override the file's own ``DIM`` line.  ``'SI'`` reads every
        length as metres — the pre-v5.46 lumenairy dialect (see
        *Migration* below).  Default ``None`` honours the file.

    Returns a dict of the same shape as :func:`make_singlet`, plus
    ``elements`` / ``all_thicknesses`` (the full chronological list
    including mirrors, matching :func:`load_zemax_zmx`'s schema):
    ``{'name', 'aperture_diameter', 'surfaces', 'thicknesses',
       'elements', 'all_thicknesses', 'wavelength', 'stop_index'}``.

    Unknown commands are silently ignored so that files written by
    CODE V with extra boilerplate (tolerancing directives, zoom
    positions, spot-diagram commands, ...) still parse.

    Migration
    ---------
    **CODE V's ``DIM M`` means MILLIMETRES.**  Before v5.46 this loader
    read it as metres and did not recognise ``C`` / ``I`` at all, so a
    genuine CODE V file imported 1000x too large in silence (measured on
    an AC254-100 sequence: radii 62.75 m instead of 62.75 mm, EFL
    72.2154 m instead of 72.2154 mm).  Both sides are fixed.

    A file this library wrote *before* v5.46 with the default ``units='M'``
    carries ``DIM M`` with SI-metre numbers.  Those files are identified
    exactly — they carry ``export_codev_seq``'s banner, **not** the
    ``LUMENAIRY-SEQ-FORMAT`` marker the fixed writer stamps, and a ``DIM M``
    line (or no ``DIM`` line) — and are read with the legacy metre scale so
    they keep round-tripping, with a :class:`UserWarning` naming the
    situation.  Pass ``dim_units='M'`` to force the CODE V reading of such a
    file, or re-export it once to stamp the marker.  A pre-v5.46 file written
    with ``units='MM'`` / ``'IN'`` needs no special handling: those tokens
    meant millimetres / inches then and still do, so such a file reads
    identically under both conventions and takes the ordinary path.
    """
    with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
        raw = f.read()

    # Strip comments (lines starting with '!') and blank lines.
    lines_iter = []
    _comments = []
    for ln in raw.splitlines():
        s = ln.strip()
        if not s:
            continue
        if s.startswith('!'):
            _comments.append(s)
            continue
        lines_iter.append(s)

    # I1 migration: a file this library wrote before v5.46 carries the writer
    # banner but no format marker, and its DIM M numbers are SI METRES.  That
    # pairing is the only way to tell such a file from a genuine CODE V one,
    # so read it on its own terms rather than silently shrinking it by 1000.
    _legacy_written_here = (
        any(c.startswith(_CV_WRITER_BANNER) for c in _comments)
        and not any(c.startswith(_CV_FORMAT_MARKER_PREFIX)
                    for c in _comments))
    # VERIFY-A10: the legacy scale is per-TOKEN, not a blanket metre scale.
    # The pre-v5.46 writer also emitted ``DIM MM`` and ``DIM IN`` (its
    # docstring advertised them as "useful for handing files to CODE V
    # users"), and those files carry millimetres / inches -- reading them as
    # metres is a 1000x / 39.37x error, which is the very defect I1 fixed
    # pointed the other way.  Pre-scan the file's own DIM token so only the
    # genuinely ambiguous ``DIM M`` (or a file with no DIM line at all) takes
    # the legacy branch.
    _file_dim_tok = None
    for _ln in lines_iter:
        _tk = _ln.split()
        if _tk and _tk[0].upper() == 'DIM' and len(_tk) >= 2:
            _file_dim_tok = _tk[1].upper()
            break
    _legacy_si = (_legacy_written_here
                  and _file_dim_tok in (None, 'M'))

    # ``dim_units`` (when given) overrides both the file and the legacy sniff.
    _forced_scale = None
    if dim_units is not None:
        _du = str(dim_units).upper()
        if _du == 'SI':
            _forced_scale = 1.0
        elif _du in _CV_DIM_TO_METERS:
            _forced_scale = _CV_DIM_TO_METERS[_du]
        else:
            raise ValueError(
                f"load_codev_seq: dim_units must be a CODE V DIM token "
                f"{sorted(_CV_DIM_TO_METERS)} or 'SI' (pre-v5.46 lumenairy "
                f"metres), got {dim_units!r}")
        _legacy_si = False
    elif _legacy_si:
        warnings.warn(
            f"load_codev_seq({os.path.basename(filepath)!r}): this file was "
            f"written by lumenairy before v5.46, when ``DIM M`` was emitted "
            f"with SI-METRE numbers (CODE V's DIM M means MILLIMETRES).  It "
            f"is being read with that legacy metre scale so the values are "
            f"unchanged from what was written.  Re-export it once to stamp "
            f"the '{_CV_FORMAT_MARKER[2:]}' marker and get a file CODE V can "
            f"read, or pass dim_units='M' to read it as true CODE V "
            f"millimetres.",
            UserWarning, stacklevel=2)

    # CODE V's own default lens unit is millimetres.
    units = 'M'
    wavelength_m = None
    aperture_diameter_m = None

    # Surface blocks as we encounter them.  `current` is a dict mutated
    # while inside S<i> / SO / SI; flushed to `surfaces` on the next
    # surface header or END.
    surfaces_raw = []
    current = None
    # Also capture the optional SI image-plane block
    # so callers can recover the BFL from a `.seq` file that uses the
    # standard CODE V convention of encoding the back-focal length on
    # the image-plane THI.
    image_plane_thi = None
    # CV-1 (AUDIT_IO_PRESCRIPTIONS): track dropped shape/fold directives so a
    # folded / aspheric ``.seq`` doesn't import as a silently straight-axis /
    # base-conic system.  CODE V encodes folds as XDE/YDE/ZDE (decenters) and
    # ADE/BDE/CDE (tilts), and aspheres via ASP/SDG -- none are parsed here,
    # so we warn once (rather than silently) that they were ignored.
    _dropped_geometry_cmds: set = set()
    _CV_FOLD_CMDS = frozenset({'XDE', 'YDE', 'ZDE', 'ADE', 'BDE', 'CDE'})
    # ``ASP`` is now a parsed declaration (its K / A..J payload is read), so
    # only ``SDG`` (the spline/deformable sag table) remains unparsed here.
    _CV_ASPHERE_CMDS = frozenset({'SDG'})

    def _unit_scale():
        """Metres per current lens unit (I1: CODE V DIM M == millimetres)."""
        if _forced_scale is not None:
            return _forced_scale
        if _legacy_si:
            # Pre-v5.46 dialect: 'M' meant METRES; 'MM' / 'IN' meant what
            # they say (and are handled by the modern table anyway, so this
            # branch is only reached for 'M' or a file with no DIM line).
            return _CV_LEGACY_TO_METERS.get(units, 1.0)
        return _CV_DIM_TO_METERS[units]

    def _unit_to_meters(v):
        if v is None:
            return None
        return _unit_scale() * float(v)

    def _flush():
        nonlocal current, image_plane_thi
        if current is not None:
            if current.get('kind') == 'refracting':
                surfaces_raw.append(current)
            elif current.get('kind') == 'image':
                # Preserve the image-plane THI for BFL recovery.
                if current.get('thickness') is not None:
                    image_plane_thi = current.get('thickness')
        current = None

    i = 0
    while i < len(lines_iter):
        tokens = lines_iter[i].split()
        cmd = tokens[0].upper()

        if cmd == 'LEN' or cmd == 'GO' or cmd == 'END' or cmd == 'REF':
            if cmd == 'END':
                _flush()
                break
            i += 1
            continue

        if cmd == 'DIM':
            if len(tokens) >= 2:
                unit_tok = tokens[1].upper()
                if unit_tok in _CV_DIM_TO_METERS:
                    units = unit_tok
                else:
                    # I1: pre-v5.46 an unrecognised token fell through to the
                    # default with no diagnostic -- an order-of-magnitude
                    # mis-scale in silence.  The Zemax loader has warned here
                    # since S4-9; match it.
                    warnings.warn(
                        f"load_codev_seq({os.path.basename(filepath)!r}): "
                        f"unrecognised DIM token {unit_tok!r}; keeping "
                        f"{units!r} ({_CV_DIM_TO_METERS[units]:g} m per lens "
                        f"unit).  CODE V's DIM tokens are M (millimetres), "
                        f"C (centimetres), I (inches).  Verify the file or "
                        f"pass dim_units= explicitly if this is wrong.",
                        UserWarning, stacklevel=2)
            i += 1
            continue

        if cmd == 'WL':
            if len(tokens) >= 2:
                try:
                    wavelength_m = float(tokens[1]) * 1e-9
                except ValueError:
                    pass
            i += 1
            continue

        if cmd == 'APE':
            # APE F1 CIR R <radius>  or  APE CIR R <radius>
            for j, tk in enumerate(tokens):
                if tk.upper() == 'R' and j + 1 < len(tokens):
                    try:
                        r = float(tokens[j + 1])
                        aperture_diameter_m = 2.0 * _unit_to_meters(r)
                    except ValueError:
                        pass
                    break
            i += 1
            continue

        # Surface headers.  Accept S<int>, SO, SI, SIM.
        if cmd == 'SO':
            _flush()
            current = {'kind': 'object'}
            i += 1
            continue
        if cmd in ('SI', 'SIM'):
            _flush()
            current = {'kind': 'image'}
            i += 1
            continue
        if cmd.startswith('S') and len(cmd) > 1 and cmd[1:].isdigit():
            _flush()
            current = {'kind': 'refracting',
                       'index': int(cmd[1:]),
                       'radius': None, 'conic': 0.0,
                       'thickness': 0.0, 'glass': 'air',
                       'is_stop': False, 'is_mirror': False,
                       'asph': {}}
            i += 1
            continue

        # Commands that apply to the current surface block
        if current is None:
            i += 1
            continue

        if cmd == 'STO':
            if current.get('kind') == 'refracting':
                current['is_stop'] = True
                # CV-nit (AUDIT_IO_PRESCRIPTIONS): dropped the dead
                # ``current['index']`` read-and-discard (refactor residue).
            i += 1
            continue

        if cmd == 'RDY':
            if len(tokens) >= 2:
                val = tokens[1]
                if val.upper() == 'INFINITY' or val.upper() == 'INF':
                    current['radius'] = float('inf')
                else:
                    try:
                        current['radius'] = _unit_to_meters(float(val))
                    except ValueError:
                        pass
            i += 1
            continue

        if cmd == 'CUY':
            if len(tokens) >= 2:
                try:
                    c = float(tokens[1])
                    # c is 1/lens-unit; R[m] = (1/c) lens-units * metres-per-unit
                    current['radius'] = (float('inf') if c == 0
                                         else (1.0 / c) * _unit_scale())
                except ValueError:
                    pass
            i += 1
            continue

        if cmd == 'THI':
            if len(tokens) >= 2:
                val = tokens[1]
                if val.upper() == 'INFINITY' or val.upper() == 'INF':
                    current['thickness'] = float('inf')
                else:
                    try:
                        current['thickness'] = _unit_to_meters(float(val))
                    except ValueError:
                        pass
            i += 1
            continue

        if cmd == 'GLA':
            if len(tokens) >= 2:
                g = tokens[1]
                current['glass'] = (
                    'air' if g.upper() in ('AIR', '') else g)
            i += 1
            continue

        # I3: ``K`` is CODE V's conic keyword; ``CON`` is the token this
        # library's own pre-v5.46 writer emitted.  Accept both -- pre-fix only
        # ``CON`` was read, so every genuine CODE V conic (``K -1.0`` on a
        # parabola) vanished with no warning.
        if cmd in ('K', 'CON'):
            if len(tokens) >= 2:
                try:
                    current['conic'] = float(tokens[1])
                except ValueError:
                    pass
            i += 1
            continue

        # I3: CODE V's even-aspheric coefficients A..J (y^4 .. y^20).  Stored
        # in the library convention a_p [m^(1-p)] via a_p = a_file /
        # L**(p-1), L = metres per lens unit -- the same rule the Zemax
        # loader applies with L = unit_scale.
        if cmd in _CV_ASPH_LETTER_TO_POWER and len(tokens) >= 2:
            try:
                _a_file = float(tokens[1])
            except ValueError:
                i += 1
                continue
            _p = _CV_ASPH_LETTER_TO_POWER[cmd]
            current['asph'][_p] = _a_file / (_unit_scale() ** (_p - 1))
            i += 1
            continue

        # I3: ``REFL`` (and the ``RMD REFL`` reflective-mode form) mark a
        # mirror.  Pre-v5.46 both fell into the silent-ignore tail, so a CODE V
        # fold or catadioptric mirror imported as an air-to-air dummy: the
        # design un-folded AND lost the mirror's optical power, with no
        # warning at all.
        if cmd == 'REFL' or (cmd == 'RMD' and len(tokens) >= 2
                             and tokens[1].upper().startswith('REFL')):
            current['is_mirror'] = True
            i += 1
            continue

        # ``ASP`` only declares that the surface is aspheric; its payload is
        # the K / A..J lines handled above.  Nothing to drop.
        if cmd == 'ASP':
            i += 1
            continue

        # CV-1: record dropped fold / aspheric directives so they can be
        # surfaced once (below) rather than silently swallowed by the
        # unknown-directive fallthrough -- a folded / aspheric .seq otherwise
        # imports as a straight-axis / base-conic system with no signal.
        if cmd in _CV_FOLD_CMDS or cmd in _CV_ASPHERE_CMDS:
            _dropped_geometry_cmds.add(cmd)
        # Unknown directive — ignore
        i += 1

    if _dropped_geometry_cmds:
        _fold = sorted(_dropped_geometry_cmds & _CV_FOLD_CMDS)
        _asph = sorted(_dropped_geometry_cmds & _CV_ASPHERE_CMDS)
        _parts = []
        if _fold:
            _parts.append(
                f"coordinate decenter/tilt (fold) directives {_fold} -- the "
                f"design imports as STRAIGHT-AXIS with the fold geometry gone")
        if _asph:
            _parts.append(
                f"aspheric directives {_asph} -- aspheric surfaces degrade to "
                f"base conic")
        warnings.warn(
            f"load_codev_seq({os.path.basename(filepath)!r}): dropped "
            f"unparsed shape/geometry directives -- "
            f"{'; '.join(_parts)}.  This loader does not yet parse them; the "
            f"loaded prescription is missing that geometry.",
            UserWarning, stacklevel=2)

    _flush()

    if not surfaces_raw:
        raise ValueError(
            f"load_codev_seq: no refracting surfaces found in "
            f"{filepath!r}.  Check the file is a valid CODE V .seq.")

    # Build the library prescription
    surfaces = []
    thicknesses = []
    elements = []
    all_thicknesses = []
    prev_glass = 'air'
    # The last refracting surface's thickness goes to the image plane,
    # not the prescription's `thicknesses` list (library convention is
    # that `thicknesses[i]` is the gap AFTER surface i, stopping at the
    # last refracting surface; the final image-plane gap is the BFL and
    # not part of the prescription).  v4.13.2 (C-P0-4): capture the
    # last surface's THI as ``back_focal_length`` (image distance) so
    # externally-authored `.seq` files where the BFL is encoded as the
    # last surface's THI -- a legitimate CODE V convention -- no longer
    # silently drop the BFL on read.  Round-trips through
    # :func:`export_codev_seq` are now lossless.
    last_surface_thickness = 0.0
    # I3: the gap that follows each element, for the ``all_thicknesses`` list
    # (``elements[i]`` -> ``elements[i+1]``); the refractive-only
    # ``thicknesses`` list below sums across any mirror in between, exactly
    # like the Zemax loader's ``lens_thicknesses``.
    gap_after = []
    for i, s in enumerate(surfaces_raw):
        # I3: ``dict.get`` returns the STORED ``None`` (the key always exists),
        # so the documented "flat surface" default never fired and a legal
        # CODE V dummy surface (THI only) produced ``radius=None``, which
        # ``validate_prescription`` rejects.  Default it here instead.
        _R = s.get('radius')
        if _R is None:
            _R = float('inf')
        _asph = s.get('asph') or None
        _is_mirror = bool(s.get('is_mirror'))
        _glass_here = s.get('glass', 'air')
        if _is_mirror:
            # A reflective surface does not introduce a new medium: the beam
            # returns through whatever it arrived in unless the file says
            # otherwise (a catadioptric back surface inside glass).
            _glass_after = (_glass_here if _glass_here not in (None, 'air')
                            else prev_glass)
            elements.append({
                'element_type': 'mirror',
                'radius': _R,
                'conic': s.get('conic', 0.0),
                'aspheric_coeffs': _asph,
                'surf_num': s.get('index', i + 1),
                'comment': '',
                'is_stop': bool(s.get('is_stop')),
            })
        else:
            _glass_after = _glass_here
            surf_dict = {
                'radius': _R,
                'conic': s.get('conic', 0.0),
                'aspheric_coeffs': _asph,
                'radius_y': None, 'conic_y': None,
                'aspheric_coeffs_y': None,
                'glass_before': prev_glass,
                'glass_after': _glass_after,
                'is_stop': bool(s.get('is_stop')),
            }
            surfaces.append(surf_dict)
            elements.append({
                'element_type': 'surface',
                'radius': _R,
                'conic': s.get('conic', 0.0),
                'aspheric_coeffs': _asph,
                'glass_before': prev_glass,
                'glass_after': _glass_after,
                'surf_num': s.get('index', i + 1),
                'comment': '',
                'is_stop': bool(s.get('is_stop')),
            })
        if i < len(surfaces_raw) - 1:
            gap_after.append(float(s.get('thickness', 0.0) or 0.0))
        else:
            last_surface_thickness = s.get('thickness', 0.0)
        prev_glass = _glass_after

    all_thicknesses = list(gap_after)
    # Refractive-only gaps: sum every element gap between consecutive
    # refracting surfaces (so a fold mirror's legs are folded flat, the same
    # collapse ``load_zemax_zmx`` makes for the unfolded prescription).
    _refr_idx = [k for k, e in enumerate(elements)
                 if e['element_type'] == 'surface']
    for j in range(len(_refr_idx) - 1):
        thicknesses.append(
            float(sum(gap_after[k]
                      for k in range(_refr_idx[j], _refr_idx[j + 1])
                      if k < len(gap_after))))

    if not surfaces:
        raise ValueError(
            f"load_codev_seq: {filepath!r} declares only reflective surfaces "
            f"(REFL / RMD REFL); the refractive 'surfaces' list is empty.  "
            f"Use the returned 'elements' list with apply_mirror, or "
            f"split_prescription_at_mirrors.")

    # Figure out the stop index (0-based among refracting surfaces).
    stop_index = None
    _refr_seen = -1
    for _s in surfaces_raw:
        _is_m = bool(_s.get('is_mirror'))
        if not _is_m:
            _refr_seen += 1
        if _s.get('is_stop'):
            # ``stop_index`` indexes the REFRACTIVE subset; a stop declared on
            # a mirror stays visible through ``elements[i]['is_stop']`` only.
            if not _is_m:
                stop_index = _refr_seen
            break

    # I7: unknown glasses.  Both Zemax loaders end with this block; without it
    # a CODE V name like ``BK7`` or a 6-digit glass code surfaced much later
    # as a ValueError from ``get_glass_index`` inside a propagation, with no
    # pointer back to the file.
    _unknown = sorted({g for e in elements
                       for g in (e.get('glass_before'), e.get('glass_after'))
                       if g and g != 'air' and g not in GLASS_REGISTRY})
    if _unknown:
        warnings.warn(
            f"load_codev_seq({os.path.basename(filepath)!r}): glasses not in "
            f"GLASS_REGISTRY: {_unknown}.  Add them before propagating. "
            f"Example:\n"
            f"  GLASS_REGISTRY['GLASS_NAME'] = ('specs', 'CATALOG', 'PAGE')\n"
            f"Browse refractiveindex.info to find the correct path.  CODE V "
            f"names are often catalogue-suffixed ('N-BK7_SCHOTT') or 6-digit "
            f"codes ('517642.514'), neither of which is a registry key.",
            UserWarning, stacklevel=2)

    result = {
        'name': name or os.path.splitext(os.path.basename(filepath))[0],
        'aperture_diameter': aperture_diameter_m or 25.4e-3,
        'surfaces': surfaces,
        'thicknesses': thicknesses,
        # I7: the schema three docstrings already promised
        # (``normalize_prescription`` / ``split_prescription_at_mirrors``).
        'elements': elements,
        'all_thicknesses': all_thicknesses,
    }
    if wavelength_m is not None:
        result['wavelength'] = wavelength_m
    if stop_index is not None:
        result['stop_index'] = stop_index
    # Preserve the BFL.  Prefer the SI image-plane
    # THI if present (matches what :func:`export_codev_seq` writes);
    # otherwise fall back to the last refracting surface's THI, which
    # is the convention used by some external CODE V authors.
    bfl = image_plane_thi
    if bfl is None or bfl == 0.0:
        bfl = last_surface_thickness
    if bfl is not None and bfl != 0.0 and np.isfinite(bfl):
        result['back_focal_length'] = float(bfl)
    return result


# A-13ish (AUDIT_ADVERSARIAL_CODEBASE 2026-07-25): declare the public
# surface explicitly, matching the convention every ``analysis/`` module
# already follows.  Every name here is re-exported through
#  ``lumenairy.io.prescriptions`` (v5.1.0 split) and the top-level facade.
__all__ = [
    'load_codev_seq',
    'export_codev_seq',
]
