"""
lumenairy.raytrace -- geometric ray tracing.

Submodules:

* :mod:`lumenairy.raytrace.core` -- ``RayBundle``, ``Surface``,
  ``trace``, ``surfaces_from_prescription``, ABCD, paraxial trace,
  fan / ring / grid bundle factories.
* :mod:`lumenairy.raytrace.bundles` -- ``BundleProtocol`` shared
  type and inter-bundle conversion utilities.
"""

from .core import (
    RayBundle,
    Surface,
    TraceResult,
    trace,
    surfaces_from_prescription,
    make_ray,
    make_fan,
    make_ring,
    make_grid,
    make_rings,
    apply_doe_phase_traced,
    trace_prescription,
    system_abcd,
    system_abcd_prescription,
    seidel_coefficients,
    seidel_prescription,
    spot_rms,
    spot_geo_radius,
    spot_diagram,
    ray_fan_data,
    ray_fan_plot,
    ray_fan_plot_prescription,
    opd_fan_data,
    through_focus_rms,
    refocus,
    find_stop,
    compute_pupils,
    lens_abcd,
    find_lenses,
    LensInfo,
    PupilInfo,
    RAY_OK,
    RAY_TIR,
    RAY_APERTURE,
    RAY_MISSED_SURFACE,
    RAY_NAN,
    RAY_EVANESCENT,
    find_paraxial_focus,
    trace_summary,
    prescription_summary,
    surfaces_from_elements,
    raytrace_system,
    # Private helpers needed by other subpackages (asymptotic uses
    # _make_bundle as a parametric ray-bundle constructor).
    _make_bundle,
)
from .bundles import (
    BundleProtocol,
    ray_to_path,
    ray_to_beamlet,
    path_to_ray,
)


__all__ = [
    'RayBundle',
    'Surface',
    'TraceResult',
    'trace',
    'surfaces_from_prescription',
    'make_ray',
    'make_fan',
    'make_ring',
    'make_grid',
    'make_rings',
    'apply_doe_phase_traced',
    'trace_prescription',
    'system_abcd',
    'system_abcd_prescription',
    'seidel_coefficients',
    'seidel_prescription',
    'spot_rms',
    'spot_geo_radius',
    'spot_diagram',
    'ray_fan_data',
    'ray_fan_plot',
    'ray_fan_plot_prescription',
    'opd_fan_data',
    'through_focus_rms',
    'refocus',
    'find_stop',
    'compute_pupils',
    'lens_abcd',
    'find_lenses',
    'LensInfo',
    'PupilInfo',
    'RAY_OK',
    'RAY_TIR',
    'RAY_APERTURE',
    'RAY_MISSED_SURFACE',
    'RAY_NAN',
    'RAY_EVANESCENT',
    'find_paraxial_focus',
    'trace_summary',
    'prescription_summary',
    'surfaces_from_elements',
    'raytrace_system',
    'BundleProtocol',
    'ray_to_path',
    'ray_to_beamlet',
    'path_to_ray',
]
