"""VERIFY-A10 -- independent re-verification of WP-A10 (audit I1-I8).

Added by the adversarial verifier, not by the work package.  Two kinds of
test live here:

* **Regression pins for defects found DURING verification** and fixed in
  WP-A10's own files: the pre-v5.46 ``DIM MM`` / ``DIM IN`` mis-read
  (``prescriptions_code_v.py``) and the ``NameError`` in the Zarr
  ``append_plane`` compression warning (``storage.py``).  Both FAIL on the
  code as committed in ``658e6142``; the pre-fix numbers are quoted in each
  docstring.
* **Independent coverage of claims the WP asserted but did not test on that
  fixture**: the edge-thickness oracle on ASPHERIC surfaces (the WP checked
  spherical shapes only), the focus-scan gate against a user merit class that
  predates the ``needs_focus_scan`` flag, and the ``x0``-outside-bounds
  warning driven end to end through a pymoo stub instead of a source-text
  ordering pin.

Per ``docs/TESTING_STANDARDS.md``: no wall-clock or speedup assertion
anywhere here; every numeric bar carries its oracle, its error floor and the
measured value; every claim is two-sided (the property holds AND its control
does not fire).
"""

from __future__ import annotations

import os
import sys
import types
import warnings

import numpy as np
import pytest

import lumenairy as la
from lumenairy.optimize import edge_thickness

# ---------------------------------------------------------------------------
# I1 -- the pre-v5.46 migration sniff must honour the file's own DIM token
# ---------------------------------------------------------------------------
#
# Reconstructed byte for byte from the PRE-fix writer (``git show
# 658e6142^:lumenairy/io/prescriptions_code_v.py``), which accepted
# ``units='M' | 'MM' | 'IN'`` and scaled by ``{'M': 1.0, 'MM': 1e3,
# 'IN': 1/0.0254}``.  Only the ``'M'`` spelling is ambiguous (it wrote SI
# metres under CODE V's millimetre token); ``'MM'`` and ``'IN'`` files carry
# millimetres and inches and mean the same thing under both conventions.
_LEGACY_HEAD = """! Generated by lumenairy (export_codev_seq)
! Singlet (N-BK7)
LEN NEW
DIM {dim}
WL 587.6000
REF 1
APE F1 CIR R {ape}
!
! Object surface
SO
  RDY INFINITY
  THI INFINITY

! Surface 1
S1
  STO
  RDY {r1}
  THI {t1}
  GLA N-BK7

! Surface 2
S2
  RDY {r2}
  THI {bfl}

! Image surface
SI
  RDY INFINITY
  THI {bfl}

GO
END
"""

# The same physical singlet -- R1 = 50 mm, R2 = -50 mm, tc = 4 mm, half
# aperture 12.7 mm, BFL 90 mm -- written in each of the pre-fix writer's
# three unit spellings.
_LEGACY_FILES = {
    'M': dict(dim='M', ape='0.012700', r1='0.05000000', r2='-0.05000000',
              t1='0.00400000', bfl='0.09000000'),
    'MM': dict(dim='MM', ape='12.700000', r1='50.00000000', r2='-50.00000000',
               t1='4.00000000', bfl='90.00000000'),
    'IN': dict(dim='IN', ape='0.500000', r1='1.96850394', r2='-1.96850394',
               t1='0.15748031', bfl='3.54330709'),
}


def _write_legacy(tmp_path, spelling):
    p = tmp_path / f'legacy_{spelling}.seq'
    p.write_text(_LEGACY_HEAD.format(**_LEGACY_FILES[spelling]))
    return str(p)


@pytest.mark.parametrize('spelling', ['MM', 'IN'])
def test_verify_i1_pre_v546_mm_and_in_files_keep_their_own_units(
        tmp_path, spelling):
    """A pre-v5.46 file written with ``units='MM'`` / ``'IN'`` must read the
    same as it always did.

    WP-A10's legacy sniff (banner present + format marker absent) applied a
    blanket SI-metre scale regardless of the file's ``DIM`` token, so these
    two spellings -- which the pre-fix docstring advertised as "useful for
    handing files to CODE V users" -- were mis-read.  Measured on the code as
    committed in ``658e6142``, on exactly the fixtures below:

        DIM MM : R1 = 50.0 m       (pre-v5.46 loader: 0.05 m)  -> x1000
        DIM IN : R1 = 1.96850394 m (pre-v5.46 loader: 0.05 m)  -> x39.37

    Bar: the file numbers are exact decimal strings and the unit factors are
    exact (1 mm = 1e-3 m; 1 in = 0.0254 m, NIST SP 811), so the only error is
    the writer's own ``%.8f`` quantisation -- 1e-8 in the file's unit, i.e.
    2e-10 relative on a 50 mm radius for ``MM`` and 5e-9 for ``IN``.  The bar
    below (rel=1e-7) sits ~1.5 decades above that floor and 6 decades below
    the smallest defect it must catch (a factor of 39).
    """
    p = _write_legacy(tmp_path, spelling)
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter('always')
        rx = la.load_codev_seq(p)
    assert rx['surfaces'][0]['radius'] == pytest.approx(50e-3, rel=1e-7), (
        f"a pre-v5.46 'DIM {spelling}' file carries "
        f"{'millimetres' if spelling == 'MM' else 'inches'}, not metres")
    assert rx['surfaces'][1]['radius'] == pytest.approx(-50e-3, rel=1e-7)
    assert rx['thicknesses'][0] == pytest.approx(4e-3, rel=1e-7)
    assert rx['aperture_diameter'] == pytest.approx(25.4e-3, rel=1e-7)
    # ... and nothing is ambiguous about such a file, so it must not warn
    # about the migration at all.
    assert not [w for w in caught if 'before v5.46' in str(w.message)], (
        "a 'DIM MM' / 'DIM IN' legacy file reads identically under both "
        "conventions -- there is nothing to warn about")


def test_verify_i1_legacy_dim_m_still_reads_as_metres_and_warns(tmp_path):
    """The control arm: ``DIM M`` IS ambiguous and must keep WP-A10's
    behaviour -- read as SI metres (so the values are unchanged from what the
    pre-v5.46 writer wrote), with the migration warning.

    Oracle: the file's own literal ``RDY 0.05000000``.
    """
    p = _write_legacy(tmp_path, 'M')
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter('always')
        rx = la.load_codev_seq(p)
    assert rx['surfaces'][0]['radius'] == pytest.approx(0.05, rel=1e-12)
    assert [w for w in caught if 'before v5.46' in str(w.message)], (
        f"the ambiguous DIM M legacy file must warn; got "
        f"{[str(w.message)[:60] for w in caught]}")
    # The documented escape hatch still forces the CODE V reading.
    with warnings.catch_warnings():
        warnings.simplefilter('ignore')
        forced = la.load_codev_seq(p, dim_units='M')
    assert forced['surfaces'][0]['radius'] == pytest.approx(5e-5, rel=1e-12)


def test_verify_i1_a_future_format_marker_is_not_read_as_legacy(tmp_path):
    """The marker is recognised by PREFIX, so a later ``LUMENAIRY-SEQ-FORMAT
    3`` file is still read in CODE V lens units.

    Pre-fix (``658e6142``) the loader matched the exact string
    ``'! LUMENAIRY-SEQ-FORMAT 2'``, so bumping the format number would have
    silently re-classified every file this library writes as pre-v5.46
    metres -- a x1000 error introduced by a one-character change.
    """
    body = _LEGACY_HEAD.format(**_LEGACY_FILES['M']).replace(
        'LEN NEW', '! LUMENAIRY-SEQ-FORMAT 3\nLEN NEW')
    p = tmp_path / 'format3.seq'
    p.write_text(body)
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter('always')
        rx = la.load_codev_seq(str(p))
    # DIM M == millimetres, so 0.05 in the file is 5e-5 m.
    assert rx['surfaces'][0]['radius'] == pytest.approx(5e-5, rel=1e-12)
    assert not [w for w in caught if 'before v5.46' in str(w.message)]


# ---------------------------------------------------------------------------
# I7 performance note 6 -- the Zarr compression warning must not crash
# ---------------------------------------------------------------------------

def test_verify_zarr_append_plane_compression_warns_instead_of_raising(
        tmp_path):
    """``append_plane(<.zarr>, compression=...)`` warns that the request is
    dropped -- it must not raise.

    WP-A10 added that warning to ``io/storage.py`` but the module has no
    ``import warnings`` (it was the only ``warnings`` reference in all 2145
    lines), so the call raised ``NameError: name 'warnings' is not defined``
    on the code as committed in ``658e6142``.  That is strictly worse than
    the silent drop the note set out to fix: a call that used to write the
    plane now writes nothing.

    Two-sided: the same call without a compression kwarg stays silent, and
    the plane is readable back in both cases.
    """
    zarr = pytest.importorskip  # noqa: F841  (documented below)
    try:
        import zarr  # noqa: F401
    except ImportError:                                  # pragma: no cover
        # TESTING_STANDARDS rule 4 forbids skipping on a RESOURCE check; a
        # missing optional BACKEND is a different thing -- there is no zarr
        # path to test at all.  Assert the import-independent half instead.
        import lumenairy.io.storage as _s
        assert 'warnings' in vars(_s) or hasattr(_s, 'warnings'), (
            'storage.py must import warnings for the zarr compression '
            'diagnostic')
        return
    from lumenairy.io import storage as S

    E = (np.arange(64, dtype=np.float64).reshape(8, 8)
         + 1j * np.arange(64, dtype=np.float64).reshape(8, 8))
    prev = S._BACKEND
    try:
        S.set_storage_backend('zarr')
        p1 = str(tmp_path / 'with_comp.zarr')
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter('always')
            S.append_plane(p1, E, dx=1e-6, label='L0',
                           compression='gzip', compression_opts=4)
        hits = [w for w in caught if 'ignores' in str(w.message)]
        assert hits, (
            f"the dropped-compression request must be diagnosed; caught "
            f"{[str(w.message)[:60] for w in caught]}")
        planes, _ = S.load_planes(p1)
        assert len(planes) == 1
        assert np.array_equal(planes[0]['field'], E.astype(planes[0]['field'].dtype))

        p2 = str(tmp_path / 'no_comp.zarr')
        with warnings.catch_warnings(record=True) as caught2:
            warnings.simplefilter('always')
            S.append_plane(p2, E, dx=1e-6, label='L0')
        assert not [w for w in caught2 if 'ignores' in str(w.message)]
    finally:
        S.set_storage_backend(prev)


# ---------------------------------------------------------------------------
# I7 -- edge_thickness on ASPHERIC surfaces (the WP verified spheres only)
# ---------------------------------------------------------------------------

def _sag_oracle(h, R, k, coeffs):
    """Independent even-asphere sag, written here from the standard form

        z(h) = c h^2 / (1 + sqrt(1 - (1+k) c^2 h^2)) + sum_p a_p h^p ,

    with c = 1/R (c = 0 for a flat surface).  Not a library call.
    """
    if not np.isfinite(R):
        z = 0.0
    else:
        c = 1.0 / R
        rad = 1.0 - (1.0 + k) * c * c * h * h
        z = c * h * h / (1.0 + np.sqrt(rad)) if rad >= 0.0 else float('nan')
    for p, a in (coeffs or {}).items():
        z = z + a * h ** float(p)
    return z


# (tag, R1, R2, tc, h, k1, k2, aspheric_1, aspheric_2)
_EDGE_SHAPES = [
    ('parabola + A4 + A6', 30e-3, -60e-3, 6e-3, 11e-3, -1.0, 0.0,
     {4: 3.2e3, 6: -1.1e8}, None),
    ('hyperbolae both sides, A4 + A8', 26e-3, -26e-3, 7e-3, 10e-3,
     -2.5, -3.0, {4: -5.0e2, 8: 2.0e12}, {4: 8.0e2, 6: 4.0e7}),
    ('oblate k>0 + A4 + A10', 40e-3, -18e-3, 4e-3, 9e-3, 2.0, 0.5,
     {4: 1.0e4}, {4: -2.0e4, 10: 7.0e16}),
    ('aspheric plano-rear', 50e-3, float('inf'), 3e-3, 12e-3, -0.7, 0.0,
     {4: 2.0e3, 6: 5.0e7}, None),
    ('knife edge, negative result', 12e-3, -12e-3, 1.0e-3, 10e-3,
     0.0, 0.0, None, None),
]


@pytest.mark.parametrize('tag,R1,R2,tc,h,k1,k2,a1,a2', _EDGE_SHAPES,
                         ids=[s[0] for s in _EDGE_SHAPES])
def test_verify_i7_edge_thickness_matches_an_independent_aspheric_sag(
        tag, R1, R2, tc, h, k1, k2, a1, a2):
    """``t_edge = tc + sag(R2,k2,h) - sag(R1,k1,h)`` against the closed form
    above, on conics and aspheres the WP's four spherical shapes did not
    reach (parabola, two hyperbolae, an oblate k > 0, a plano rear, and a
    genuine knife edge whose answer is negative).

    Bar derivation: both sides evaluate the same exact expression in float64
    on O(1e-3) m quantities, so the floor is a handful of ULPs of the largest
    intermediate -- ~1e-19 m.  Measured worst |delta| over these five shapes
    plus the WP's four on 2026-09-12: 8.7e-19 m.  The bar 1e-15 m therefore
    sits ~3 decades above the float64 floor and ~12 decades below the
    smallest edge-thickness error that could matter optically (1 um).
    """
    rx = la.make_singlet(R1, R2, tc, 'N-BK7', aperture=2 * h)
    rx['surfaces'][0]['conic'] = k1
    rx['surfaces'][1]['conic'] = k2
    rx['surfaces'][0]['aspheric_coeffs'] = a1
    rx['surfaces'][1]['aspheric_coeffs'] = a2
    got = edge_thickness(rx, 0)
    expected = tc + _sag_oracle(h, R2, k2, a2) - _sag_oracle(h, R1, k1, a1)
    assert np.isfinite(expected), 'fixture must be well defined at h'
    assert abs(got - expected) < 1e-15, (
        f'{tag}: edge_thickness {got!r} vs independent sag {expected!r}')


def test_verify_i7_undefined_edge_is_a_maximal_violation():
    """A surface that does not reach the clear semi-diameter (R = 8 mm at
    h = 10 mm) has no sag, so ``edge_thickness`` is ``nan`` -- and the merit
    must score that slot as a MAXIMAL violation, not skip it (V3).

    Pre-fix (`658e6142` .. VERIFY-A10 §2) the NaN slot was ``continue``-d, so
    the contribution was **0.0**: an element whose surfaces do not even reach
    their own rim scored as *satisfying* a manufacturability constraint,
    precisely where the constraint bites.  That is the reward-the-failure
    shape S4-5 fixed for a NaN ``strehl_best`` in ``driver.py``.

    Bar derivation: with the slot unmeasurable the deficit is the whole
    budget, so the contribution is exactly ``weight * min_edge**2`` --
    ``1.0 * (1e-3)**2 = 1e-6`` -- an exact product of two
    double-representable numbers, hence the ``rel=1e-15`` (one rounding).
    Two-sided: a WELL-DEFINED knife edge is still penalised by its own
    (smaller) deficit, and a healthy element still scores 0.
    """
    from lumenairy.optimize import MinEdgeThicknessMerit
    rx = la.make_singlet(8e-3, -8e-3, 2e-3, 'N-BK7', aperture=20e-3)
    assert np.isnan(edge_thickness(rx, 0)), (
        'fixture must actually produce an unmeasurable edge')

    class _Ctx:
        prescription = rx
    merit = MinEdgeThicknessMerit(min_edge=1e-3)
    assert merit.evaluate(_Ctx()) == pytest.approx(1e-6, rel=1e-15), (
        'an unmeasurable edge must cost the full min_edge**2, not 0.0')

    # A well-defined knife edge: t_edge = -9.7335e-3 m, so the deficit is
    # 1e-3 - (-9.7335e-3) = 1.07335e-2 and the contribution 1.152e-4 -- larger
    # than the NaN case, i.e. the ordering "measurably worse > unmeasurable"
    # is preserved and the NaN arm is not swamping real geometry.
    rx2 = la.make_singlet(12e-3, -12e-3, 1e-3, 'N-BK7', aperture=20e-3)

    class _Ctx2:
        prescription = rx2
    knife = MinEdgeThicknessMerit(min_edge=1e-3).evaluate(_Ctx2())
    assert knife > 1e-6

    # ... and a healthy element still scores exactly zero.
    rx3 = la.make_singlet(60e-3, -60e-3, 6e-3, 'N-BK7', aperture=10e-3)

    class _Ctx3:
        prescription = rx3
    assert np.isfinite(edge_thickness(rx3, 0))
    assert MinEdgeThicknessMerit(min_edge=1e-3).evaluate(_Ctx3()) == 0.0


# ---------------------------------------------------------------------------
# I7 -- the focus-scan gate and a merit class that predates the flag
# ---------------------------------------------------------------------------

def test_verify_i7_focus_scan_runs_for_a_merit_class_without_the_flag(
        monkeypatch):
    """A user merit written before ``needs_focus_scan`` existed declares only
    ``needs_wave`` and may read ``ctx.strehl_best`` / ``ctx.z_best``.  The
    gate's ``getattr(m, 'needs_focus_scan', True)`` default must keep the
    scan for it, and the values it reads must be the real ones.

    Counted, not timed (TESTING_STANDARDS S1).  Measured 2026-09-12 on the
    fixture below: 5 scan calls / 155 slices with the legacy merit, and the
    merit saw a non-zero ``strehl_best`` on all 5 evaluations; the same run
    with ``RMSWavefrontMerit`` alone in the wave slot gives 0 / 0.
    """
    import lumenairy.optimize.core as _opt_core
    from lumenairy.optimize.core import MeritTerm

    class _LegacyWaveMerit(MeritTerm):
        needs_wave = True
        name = 'LegacyWave'

        def __init__(self):
            self.seen = []

        def evaluate(self, ctx):
            self.seen.append((ctx.z_best, ctx.strehl_best))
            return (1.0 - ctx.strehl_best) ** 2

    counters = {'calls': 0, 'slices': 0}
    orig = _opt_core.through_focus_scan

    def counting_scan(E, dx, wl, zs, **kw):
        counters['calls'] += 1
        counters['slices'] += len(zs)
        return orig(E, dx, wl, zs, **kw)
    monkeypatch.setattr(_opt_core, 'through_focus_scan', counting_scan)

    template = la.make_singlet(50e-3, -50e-3, 4e-3, 'N-BK7', aperture=6e-3)
    param = la.DesignParameterization(
        template=template, free_vars=[('surfaces', 0, 'radius')],
        bounds=[(30e-3, 80e-3)])
    legacy = _LegacyWaveMerit()
    with warnings.catch_warnings():
        warnings.simplefilter('ignore')
        la.design_optimize(param,
                           [la.FocalLengthMerit(target=100e-3), legacy],
                           wavelength=587.6e-9, N=64, dx=20e-6,
                           method='L-BFGS-B', max_iter=1, verbose=False)
    assert counters['calls'] >= 1, (
        'the gate must default to running the scan for a merit class that '
        'does not declare needs_focus_scan')
    assert counters['slices'] == 31 * counters['calls']
    assert legacy.seen and all(s != 0.0 for _z, s in legacy.seen), (
        f'the legacy merit must see real focus results, got {legacy.seen}')

    # Control: swap the legacy merit for a library merit that declares it
    # does NOT read the scan, and the scan disappears.
    counters['calls'] = counters['slices'] = 0
    with warnings.catch_warnings():
        warnings.simplefilter('ignore')
        la.design_optimize(param,
                           [la.FocalLengthMerit(target=100e-3),
                            la.RMSWavefrontMerit(max_rms_waves=0.07)],
                           wavelength=587.6e-9, N=64, dx=20e-6,
                           method='L-BFGS-B', max_iter=1, verbose=False)
    assert counters['calls'] == 0 and counters['slices'] == 0


# ---------------------------------------------------------------------------
# I8 -- x0 vs bounds, driven END TO END through a pymoo stub
# ---------------------------------------------------------------------------

def _install_pymoo_stub(monkeypatch, feasible=True):
    """A minimal stand-in reproducing pymoo's documented API surface and its
    infeasible-run contract (``Result.X`` / ``Result.F`` are ``None``).

    Written here rather than imported so the assertion below does not depend
    on pymoo being installed -- and so the test is a BEHAVIOUR check, not the
    source-text ordering pin the work package used (which passes even if the
    check is disabled).
    """
    import importlib.machinery as _mach

    class _Problem:
        def __init__(self, *a, **k):
            self.n_var = k.get('n_var', 1)
            self.n_obj = k.get('n_obj', 2)
            self.xl = k.get('xl')
            self.xu = k.get('xu')

    def _minimize(problem, algorithm, termination, **kw):
        n = getattr(problem, 'n_var', 1)
        X = np.atleast_2d(np.linspace(0.1, 0.9, 5 * n).reshape(5, n))
        rows = []
        for row in X:
            out = {}
            problem._evaluate(row, out)
            rows.append(np.ravel(out['F']))
        res = types.SimpleNamespace()
        if feasible:
            res.X, res.F = X, np.asarray(rows, dtype=float)
            res.CV = np.zeros((X.shape[0], 1))
        else:
            res.X = res.F = None
            res.CV = np.full((X.shape[0], 1), 3.25)
        return res

    class _NSGA2:
        def __init__(self, *a, **k):
            pass

    class _MaxGen:
        def __init__(self, *a, **k):
            pass

    mods = {}
    for name in ('pymoo', 'pymoo.core', 'pymoo.core.problem',
                 'pymoo.algorithms', 'pymoo.algorithms.moo',
                 'pymoo.algorithms.moo.nsga2', 'pymoo.optimize',
                 'pymoo.termination', 'pymoo.termination.max_gen',
                 'pymoo.operators'):
        m = types.ModuleType(name)
        m.__spec__ = _mach.ModuleSpec(name, None)
        m.__loader__ = None
        mods[name] = m
    mods['pymoo.core.problem'].Problem = _Problem
    mods['pymoo.core.problem'].ElementwiseProblem = _Problem
    mods['pymoo.algorithms.moo.nsga2'].NSGA2 = _NSGA2
    mods['pymoo.optimize'].minimize = _minimize
    mods['pymoo.termination.max_gen'].MaximumGenerationTermination = _MaxGen
    for name, m in mods.items():
        monkeypatch.setitem(sys.modules, name, m)
    from lumenairy.optimize import multi_objective as mo
    monkeypatch.setattr(mo, 'PYMOO_AVAILABLE', True)
    return mo


def test_verify_i8_x0_outside_bounds_warns_end_to_end(monkeypatch):
    """The docstring's "sanity check against bounds" must actually fire, and
    only when ``x0`` is outside the box.

    The work package pinned this by asserting the ORDER of two substrings in
    ``inspect.getsource`` and skipping when pymoo is present -- which passes
    for a disabled check and removes the test on exactly the runners that
    have the dependency (TESTING_STANDARDS rule 4).  Driving the stub gives
    the same coverage with no skip and no source-text dependency.
    """
    mo = _install_pymoo_stub(monkeypatch, feasible=True)
    merits = [lambda x: float(np.sum(x)), lambda x: float(-np.sum(x))]

    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter('always')
        mo.design_optimize_multi_objective(
            merits, x0=np.array([5.0]), bounds=[(0.0, 1.0)],
            n_generations=2, pop_size=5)
    assert [w for w in caught if 'OUTSIDE bounds' in str(w.message)], (
        f'x0 = 5.0 outside [0, 1] must warn; caught '
        f'{[str(w.message)[:60] for w in caught]}')

    with warnings.catch_warnings(record=True) as caught2:
        warnings.simplefilter('always')
        mo.design_optimize_multi_objective(
            merits, x0=np.array([0.5]), bounds=[(0.0, 1.0)],
            n_generations=2, pop_size=5)
    assert not [w for w in caught2 if 'OUTSIDE bounds' in str(w.message)]


def test_verify_i7_infeasible_front_refuses_with_and_without_progress(
        monkeypatch):
    """``Result.X is None`` must raise, on both the plain and the
    ``progress=`` path -- pre-fix the first returned a 0-d NaN array as the
    Pareto front and the second raised ``IndexError: tuple index out of
    range`` from ``X.shape[0]``.

    The numpy step the whole finding rests on is measured here, not assumed.
    """
    assert np.asarray(None, dtype=np.float64).ndim == 0
    mo = _install_pymoo_stub(monkeypatch, feasible=False)
    merits = [lambda x: float(np.sum(x)), lambda x: float(-np.sum(x))]
    for progress in (None, lambda *a, **k: None):
        with pytest.raises(ValueError, match='NO feasible solution'):
            mo.design_optimize_multi_objective(
                merits, x0=np.array([0.5]), bounds=[(0.0, 1.0)],
                n_generations=3, pop_size=5, progress=progress)


# ---------------------------------------------------------------------------
# I3 -- a genuine CODE V file in INCHES with a fold mirror, round-tripped
# ---------------------------------------------------------------------------

_INCH_SEQ = """! human-written CODE V sequence: inches, parabola + fold mirror
LEN NEW
DIM I
WL 632.8
REF 1
SO
  RDY INFINITY
  THI INFINITY
S1
  STO
  RDY 2.0
  THI 0.25
  GLA N-BK7
  ASP
  K -1.0
  A 1.000000E-04
  B -2.500000E-06
  J 7.000000E-15
S2
  RDY INFINITY
  THI 1.5
S3
  RDY -3.5
  THI 2.0
  REFL
S4
  RDY 4.0
  THI 0.2
  GLA N-SF11
S5
  RDY INFINITY
  THI 3.0
SI
  RDY INFINITY
  THI 0.0
GO
END
"""


def test_verify_i3_inch_file_with_a_fold_mirror_round_trips(tmp_path):
    """A fixture the work package did not use: inches (``DIM I``), a
    parabola carrying ``A``/``B``/``J`` (y^4, y^6, y^20), and a fold mirror
    in AIR between two glass elements.

    Oracles, all computed here: the inch definition (0.0254 m exactly), the
    lens-unit rescale ``a_p = a_file / L**(p-1)``, and the requirement that
    the mirror's two legs (1.5 in + 2.0 in) fold into ONE refractive gap.

    Bars: the coefficient and radius identities are exact products of
    double-representable numbers, so ``rel=1e-15`` is one rounding above the
    floor; the round-trip bar is ``rel=1e-9``, one decade above the writer's
    ``%.10E`` / ``%.8f`` quantisation (2e-10 relative on a 50 mm radius).
    """
    p = tmp_path / 'inch_fold.seq'
    p.write_text(_INCH_SEQ)
    L = 0.0254
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter('always')
        rx = la.load_codev_seq(str(p))
    assert not caught, [str(w.message)[:70] for w in caught]

    assert rx['surfaces'][0]['radius'] == pytest.approx(2.0 * L, rel=1e-15)
    assert rx['surfaces'][0]['conic'] == -1.0
    asph = rx['surfaces'][0]['aspheric_coeffs']
    for power, a_file in ((4, 1.0e-4), (6, -2.5e-6), (20, 7.0e-15)):
        assert asph[power] == pytest.approx(a_file / L ** (power - 1),
                                            rel=1e-15), f'A_{power}'

    types_ = [e['element_type'] for e in rx['elements']]
    assert types_ == ['surface', 'surface', 'mirror', 'surface', 'surface']
    assert la.has_mirrors(rx)
    # The mirror's legs (1.5 + 2.0 inches) collapse into one refractive gap.
    assert rx['all_thicknesses'] == pytest.approx(
        [0.25 * L, 1.5 * L, 2.0 * L, 0.2 * L], rel=1e-15)
    assert rx['thicknesses'] == pytest.approx(
        [0.25 * L, 3.5 * L, 0.2 * L], rel=1e-15)

    q = tmp_path / 'inch_fold_rt.seq'
    with warnings.catch_warnings(record=True) as w2:
        warnings.simplefilter('always')
        la.export_codev_seq(rx, str(q), wavelength=632.8e-9, units='I',
                            back_focal_length=rx.get('back_focal_length', 0.0))
        back = la.load_codev_seq(str(q))
    assert not w2, [str(x.message)[:70] for x in w2]
    assert [e['element_type'] for e in back['elements']] == types_
    for a, b in zip(rx['elements'], back['elements']):
        if np.isfinite(a['radius']):
            assert b['radius'] == pytest.approx(a['radius'], rel=1e-9)
        else:
            assert not np.isfinite(b['radius'])
        assert b['conic'] == pytest.approx(a['conic'], abs=1e-9)
        if a['aspheric_coeffs']:
            for k, v in a['aspheric_coeffs'].items():
                assert b['aspheric_coeffs'][k] == pytest.approx(v, rel=1e-9)
    assert back['thicknesses'] == pytest.approx(rx['thicknesses'], rel=1e-9)


def test_verify_i5_hostile_glass_token_never_reaches_a_code_position(
        tmp_path):
    """Payloads of the verifier's own construction (quote-escape, both
    quote styles, a backslash, a U+2028 line separator, a ``\"\"\"``
    terminator) must appear only inside string constants of the generated
    script -- never as a Call node.

    Oracle: Python's own ``ast``.  A ``Call`` whose callee is named
    ``system`` / ``__import__`` / ``eval`` / ``exec`` is live code; pre-fix
    the audit's payload produced exactly that (the emitted GLASS_REGISTRY
    line parsed as TWO statements).
    """
    import ast

    from lumenairy.io.codegen import generate_simulation_script

    payloads = [
        "X'];__import__('os').system('echo MARK');_z=['y",
        'X"];__import__("os").system("echo MARK");_z=["y',
        "X\\\\'];__import__('os').system('echo MARK');_z=['y",
        "X\u2028__import__('os').system('echo MARK')\u2028_z='y",
        'X"""+__import__("os").system("echo MARK")+"""y',
    ]
    zmx_tmpl = (
        'VERS 210000 0 123 0 0\nMODE SEQ\nUNIT MM X W X CM MR CPMM\n'
        'SURF 0\n  TYPE STANDARD\n  CURV 0\n  DISZ INFINITY\n'
        'SURF 1\n  TYPE STANDARD\n  STOP\n  CURV 0.02\n  DISZ 5.0\n'
        '  GLAS {glas} 0 0 1.5 50 0 0 0 0 0 0\n  COMM {comm}\n  DIAM 12.7\n'
        'SURF 2\n  TYPE STANDARD\n  CURV 0\n  DISZ 50.0\n  DIAM 12.7\n'
        'SURF 3\n  TYPE STANDARD\n  CURV 0\n  DISZ 0\n  DIAM 12.7\n')
    for i, payload in enumerate(payloads):
        one = payload.replace('\n', ' ')
        tok = one.split()[0] if one.split() else 'X'
        f = tmp_path / f'evil_{i}.zmx'
        f.write_text(zmx_tmpl.format(glas=tok, comm=one), encoding='utf-8')
        with warnings.catch_warnings():
            warnings.simplefilter('ignore')
            rx = la.load_zemax_zmx(str(f))
            rx['name'] = payload            # the third attack surface
            src = generate_simulation_script(
                rx, wavelength=1.31e-6, N=32,
                include_plotting=False, include_analysis=False)
        tree = ast.parse(src)               # must still be valid Python
        live = []
        for node in ast.walk(tree):
            if isinstance(node, ast.Call):
                fn = node.func
                nm = (fn.id if isinstance(fn, ast.Name)
                      else getattr(fn, 'attr', ''))
                if nm in ('system', 'popen', 'eval', 'exec', '__import__'):
                    live.append((nm, node.lineno))
            if isinstance(node, (ast.Import, ast.ImportFrom)):
                names = [a.name.split('.')[0] for a in node.names]
                assert not ({'os', 'subprocess', 'socket'} & set(names)), (
                    f'payload {i} injected an import: {names}')
        assert not live, f'payload {i} reached a code position: {live}'


def test_verify_i5_an_ordinary_zmx_still_generates_a_runnable_script(
        tmp_path):
    """Two-sided control for the injection guards: a real vendor file still
    produces a script that parses, so the sanitiser is not simply breaking
    codegen.
    """
    import ast

    from lumenairy.io.codegen import generate_simulation_script
    here = os.path.dirname(os.path.dirname(os.path.dirname(
        os.path.abspath(__file__))))
    zmx = os.path.join(here, 'validation', 'real_lens_opd',
                       'zemax_prescriptions', 'AC254_100_C.zmx')
    if not os.path.exists(zmx):             # pragma: no cover
        zmx = os.path.join(os.getcwd(), 'validation', 'real_lens_opd',
                           'zemax_prescriptions', 'AC254_100_C.zmx')
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter('always')
        rx = la.load_zemax_zmx(zmx)
        src = generate_simulation_script(rx, wavelength=1.31e-6, N=32,
                                         include_plotting=False,
                                         include_analysis=False)
    ast.parse(src)
    assert not [w for w in caught if 'injection attempt' in str(w.message)]
    assert 'N-BAF10' in src and 'N-SF6HT' in src


# ---------------------------------------------------------------------------
# V7 -- the PRESCRIPTION DATA (.txt) twin loader gets the I2 window fix too
# ---------------------------------------------------------------------------

def _txt(tmp_path, name, rows, units='Millimeters'):
    """Write a minimal Zemax ``PRESCRIPTION DATA`` report.

    Columns are TAB-separated, as the real report is: Surf, Type, Radius,
    Thickness, Glass, Clear Diam, Chip Zone, Mech Diam, Conic, Comment.
    """
    head = (f"System/Prescription Data\n\n"
            f"Primary Wavelength [um] : 1.31\n"
            f"Lens Units              : {units}\n\n"
            f"SURFACE DATA SUMMARY:\n\n"
            f"Surf\tType\tRadius\tThickness\tGlass\tClear Diam\tChip Zone"
            f"\tMech Diam\tConic\tComment\n")
    body = ''.join('\t'.join(r) + '\n' for r in rows)
    p = tmp_path / name
    p.write_text(head + body + "\nSURFACE DATA DETAIL:\n", encoding='utf-8')
    return str(p)


def _row(surf, typ, radius, thick, glass='', diam='25.400000', conic='0.0',
         comment=''):
    return [surf, typ, radius, thick, glass, diam, '0.0', diam, conic, comment]


def test_verify_v7_txt_loader_keeps_a_powered_air_to_air_surface(tmp_path):
    """``load_zemax_prescription_data_txt`` must use the same window predicate
    as ``load_zemax_zmx``.

    I2 landed on the ``.zmx`` side only: this loader's auto-detect was still
    ``glass is not None or is_mirror``, so a ``PARAXIAL`` row ahead of the
    glass -- and the STOP flag on it -- was deleted before any diagnostic
    could fire.  Measured on the code as committed in ``658e6142`` with the
    fixture below: 2 surfaces, ``stop_index`` None, and **no warning**.

    Oracle: the file's own surface list.  After: the PARAXIAL row is inside
    the window (3 surfaces), its STOP survives, and the P3-43 non-STANDARD
    warning fires for it -- which is the whole point of admitting it.
    """
    rows = [
        _row('OBJ', 'STANDARD', 'Infinity', 'Infinity', diam='0.0'),
        _row('STO', 'PARAXIAL', '100.000000', '100.000000',
             comment='ideal lens f=100'),
        _row('2', 'STANDARD', '50.000000', '5.000000', glass='N-BK7'),
        _row('3', 'STANDARD', 'Infinity', '95.000000'),
        _row('IMA', 'STANDARD', 'Infinity', '0.000000', diam='0.0'),
    ]
    p = _txt(tmp_path, 'paraxial_summary.txt', rows)
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter('always')
        rx = la.load_zemax_prescription_data_txt(p)
    assert len(rx['surfaces']) == 3, (
        f"the PARAXIAL row must be in the window; got radii "
        f"{[s['radius'] for s in rx['surfaces']]}")
    assert rx['surfaces'][0]['radius'] == pytest.approx(0.1, rel=1e-12)
    assert rx['stop_index'] == 0, 'the STOP on the PARAXIAL row must survive'
    assert [w for w in caught if 'PARAXIAL' in str(w.message)], (
        f"admitting the surface must let the P3-43 diagnostic fire; caught "
        f"{[str(w.message)[:60] for w in caught]}")


def test_verify_v7_txt_loader_warns_about_a_surface_the_window_excludes(
        tmp_path):
    """The belt-and-braces half: a row the predicate cannot admit (the summary
    table has no PARM columns, P3-43, so a FLAT ideal lens carries no power
    the loader can see) must still be NAMED, not dropped in silence.

    Shares ``_warn_window_excluded_powered`` with the ``.zmx`` loader, so the
    two diagnostics cannot drift apart.
    """
    rows = [
        _row('OBJ', 'STANDARD', 'Infinity', 'Infinity', diam='0.0'),
        _row('STO', 'PARAXIAL', 'Infinity', '100.000000',
             comment='flat ideal lens'),
        _row('2', 'STANDARD', '50.000000', '5.000000', glass='N-BK7'),
        _row('3', 'STANDARD', 'Infinity', '95.000000'),
        _row('IMA', 'STANDARD', 'Infinity', '0.000000', diam='0.0'),
    ]
    p = _txt(tmp_path, 'flat_paraxial.txt', rows)
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter('always')
        rx = la.load_zemax_prescription_data_txt(p)
    assert len(rx['surfaces']) == 2          # the glass pair only
    hits = [w for w in caught if 'EXCLUDES' in str(w.message)]
    assert hits, (
        f"the excluded STOP-bearing row must be named; caught "
        f"{[str(w.message)[:70] for w in caught]}")
    assert 'STOP' in str(hits[0].message)


def test_verify_v7_an_ordinary_txt_doublet_gains_no_new_diagnostic(tmp_path):
    """Two-sided control: an ordinary all-STANDARD design must load exactly as
    before, with no excluded-surface warning.
    """
    rows = [
        _row('OBJ', 'STANDARD', 'Infinity', 'Infinity', diam='0.0'),
        _row('STO', 'STANDARD', '62.750000', '4.000000', glass='N-BAF10'),
        _row('2', 'STANDARD', '-45.710000', '2.500000', glass='N-SF6HT'),
        _row('3', 'STANDARD', '-128.230000', '95.000000'),
        _row('IMA', 'STANDARD', 'Infinity', '0.000000', diam='0.0'),
    ]
    p = _txt(tmp_path, 'doublet.txt', rows)
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter('always')
        rx = la.load_zemax_prescription_data_txt(p)
    assert len(rx['surfaces']) == 3
    assert rx['surfaces'][0]['radius'] == pytest.approx(62.75e-3, rel=1e-12)
    assert rx['stop_index'] == 0
    assert not [w for w in caught if 'EXCLUDES' in str(w.message)]


# ---------------------------------------------------------------------------
# V10 -- _comment_text strips every str.splitlines() boundary
# ---------------------------------------------------------------------------

def test_verify_v10_no_unicode_line_separator_reaches_a_generated_script(
        tmp_path):
    """No character that ``str.splitlines()`` treats as a line boundary may
    survive into an emitted script.

    U+0085 / U+2028 / U+2029 sit outside the C0 range the comment sanitiser
    stripped.  ``_comment_text`` happened to catch them anyway (its trailing
    whitespace collapse matches Unicode whitespace), but the per-lens
    ``# {comment}`` line in the unrolled emitter did not call it at all --
    measured on ``658e6142``: exactly one line of the generated script
    carried a RAW U+2028, and it was that one.

    CPython does not treat these as SOURCE newlines (measured at the end), so
    this was never exploitable; the defect is that a tool re-reading the
    script line by line disagrees with the compiler about where the comment
    ends.  Two-sided: the payload text still appears, joined onto one line, so
    the comment is not simply being dropped.

    (The separators are built with ``chr()`` on purpose -- a literal U+2028 in
    a source file is invisible and editor-fragile.)
    """
    import ast

    from lumenairy.io.codegen import _comment_text, generate_simulation_script
    LS, PS, NEL = chr(0x2028), chr(0x2029), chr(0x85)
    # The leaking site is the per-lens ``# {comment}`` line, whose text
    # is the FIRST surface's COMM -- so the payload has to go there.
    MARKS = 'MARKA' + LS + 'MARKB' + PS + 'MARKC' + NEL + 'MARKD'

    # the unit half
    probe = 'a' + LS + 'b' + PS + 'c' + NEL + 'd\ne\tf'
    out = _comment_text(probe)
    assert len(out.splitlines()) == 1, ascii(out)
    assert out == 'a b c d e f'

    # the end-to-end half: the site that actually leaked
    zmx = (
        'VERS 210000 0 123 0 0\nMODE SEQ\nUNIT MM X W X CM MR CPMM\n'
        'SURF 0\n  TYPE STANDARD\n  CURV 0\n  DISZ INFINITY\n'
        'SURF 1\n  TYPE STANDARD\n  STOP\n  CURV 0.02\n  DISZ 5.0\n'
        '  GLAS N-BK7 0 0 1.5 50 0 0 0 0 0 0\n'
        '  COMM ' + MARKS + '\n  DIAM 12.7\n'
        'SURF 2\n  TYPE STANDARD\n  CURV 0\n  DISZ 50.0\n  DIAM 12.7\n'
        'SURF 3\n  TYPE STANDARD\n  CURV 0\n  DISZ 0\n  DIAM 12.7\n')
    f = tmp_path / 'sep.zmx'
    f.write_text(zmx, encoding='utf-8')
    with warnings.catch_warnings():
        warnings.simplefilter('ignore')
        rx = la.load_zemax_zmx(str(f))
        rx['name'] = MARKS
        src = generate_simulation_script(rx, wavelength=1.31e-6, N=32,
                                         include_plotting=False,
                                         include_analysis=False)
    for ch, nm in ((LS, 'U+2028'), (PS, 'U+2029'), (NEL, 'U+0085')):
        hits = [i for i, ln in enumerate(src.split('\n'), 1) if ch in ln]
        assert not hits, f'{nm} survived into the generated script, line {hits}'
    assert 'MARKA MARKB MARKC MARKD' in src   # still present, one line
    ast.parse(src)                            # and still compiles

    # why this was inert, measured rather than assumed: U+2028 is NOT a
    # source-line terminator for CPython's tokenizer.
    ns = {}
    exec(compile("q = 'a" + LS + "b'\n", '<probe>', 'exec'), ns)
    assert ns['q'] == 'a' + LS + 'b'


# ---------------------------------------------------------------------------
# V11 -- codegen on a raw builder prescription
# ---------------------------------------------------------------------------

def test_verify_v11_codegen_on_builder_output_names_the_fix():
    """A prescription straight from a builder raised a bare
    ``KeyError: 'elements'`` from ``_decompose_prescription``.

    Pre-existing (identical on ``658e6142^``), but it is the same class as the
    I7 ``KeyError: 'element_type'`` the work package closed, and the message
    now follows CONVENTIONS §2 and names the one-line fix.  Two-sided: the
    normalised prescription still generates a script that parses.
    """
    import ast

    from lumenairy.io.codegen import generate_simulation_script
    rx = la.make_singlet(50e-3, -50e-3, 4e-3, 'N-BK7', aperture=10e-3)
    with pytest.raises(KeyError) as exc:
        generate_simulation_script(rx, wavelength=633e-9, N=32,
                                   include_plotting=False,
                                   include_analysis=False)
    msg = str(exc.value)
    assert 'generate_simulation_script:' in msg     # CONVENTIONS section 2
    assert 'normalize_prescription' in msg
    assert "'elements'" in msg and "'all_thicknesses'" in msg

    src = generate_simulation_script(
        la.normalize_prescription(rx), wavelength=633e-9, N=32,
        include_plotting=False, include_analysis=False)
    ast.parse(src)
